// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/entitlementevent"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// EntitlementEvent is the model entity for the EntitlementEvent schema.
type EntitlementEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// subscription | balance | concurrency
	Kind string `json:"kind,omitempty"`
	// redeem | paid | manual
	Source string `json:"source,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// ValidityDays holds the value of the "validity_days" field.
	ValidityDays *int `json:"validity_days,omitempty"`
	// BalanceDelta holds the value of the "balance_delta" field.
	BalanceDelta *float64 `json:"balance_delta,omitempty"`
	// ConcurrencyDelta holds the value of the "concurrency_delta" field.
	ConcurrencyDelta *int `json:"concurrency_delta,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID *int64 `json:"order_id,omitempty"`
	// RedeemCodeID holds the value of the "redeem_code_id" field.
	RedeemCodeID *int64 `json:"redeem_code_id,omitempty"`
	// ActorUserID holds the value of the "actor_user_id" field.
	ActorUserID *int64 `json:"actor_user_id,omitempty"`
	// Note holds the value of the "note" field.
	Note *string `json:"note,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EntitlementEventQuery when eager-loading is set.
	Edges        EntitlementEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EntitlementEventEdges holds the relations/edges for other nodes in the graph.
type EntitlementEventEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Order holds the value of the order edge.
	Order *PaymentOrder `json:"order,omitempty"`
	// RedeemCode holds the value of the redeem_code edge.
	RedeemCode *RedeemCode `json:"redeem_code,omitempty"`
	// ActorUser holds the value of the actor_user edge.
	ActorUser *User `json:"actor_user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntitlementEventEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntitlementEventEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntitlementEventEdges) OrderOrErr() (*PaymentOrder, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// RedeemCodeOrErr returns the RedeemCode value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntitlementEventEdges) RedeemCodeOrErr() (*RedeemCode, error) {
	if e.RedeemCode != nil {
		return e.RedeemCode, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: redeemcode.Label}
	}
	return nil, &NotLoadedError{edge: "redeem_code"}
}

// ActorUserOrErr returns the ActorUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntitlementEventEdges) ActorUserOrErr() (*User, error) {
	if e.ActorUser != nil {
		return e.ActorUser, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "actor_user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntitlementEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entitlementevent.FieldBalanceDelta:
			values[i] = new(sql.NullFloat64)
		case entitlementevent.FieldID, entitlementevent.FieldUserID, entitlementevent.FieldGroupID, entitlementevent.FieldValidityDays, entitlementevent.FieldConcurrencyDelta, entitlementevent.FieldOrderID, entitlementevent.FieldRedeemCodeID, entitlementevent.FieldActorUserID:
			values[i] = new(sql.NullInt64)
		case entitlementevent.FieldKind, entitlementevent.FieldSource, entitlementevent.FieldNote:
			values[i] = new(sql.NullString)
		case entitlementevent.FieldCreatedAt, entitlementevent.FieldUpdatedAt, entitlementevent.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntitlementEvent fields.
func (_m *EntitlementEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entitlementevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case entitlementevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case entitlementevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case entitlementevent.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case entitlementevent.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case entitlementevent.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case entitlementevent.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case entitlementevent.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case entitlementevent.FieldValidityDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field validity_days", values[i])
			} else if value.Valid {
				_m.ValidityDays = new(int)
				*_m.ValidityDays = int(value.Int64)
			}
		case entitlementevent.FieldBalanceDelta:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_delta", values[i])
			} else if value.Valid {
				_m.BalanceDelta = new(float64)
				*_m.BalanceDelta = value.Float64
			}
		case entitlementevent.FieldConcurrencyDelta:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency_delta", values[i])
			} else if value.Valid {
				_m.ConcurrencyDelta = new(int)
				*_m.ConcurrencyDelta = int(value.Int64)
			}
		case entitlementevent.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = new(int64)
				*_m.OrderID = value.Int64
			}
		case entitlementevent.FieldRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field redeem_code_id", values[i])
			} else if value.Valid {
				_m.RedeemCodeID = new(int64)
				*_m.RedeemCodeID = value.Int64
			}
		case entitlementevent.FieldActorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actor_user_id", values[i])
			} else if value.Valid {
				_m.ActorUserID = new(int64)
				*_m.ActorUserID = value.Int64
			}
		case entitlementevent.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = new(string)
				*_m.Note = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EntitlementEvent.
// This includes values selected through modifiers, order, etc.
func (_m *EntitlementEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the EntitlementEvent entity.
func (_m *EntitlementEvent) QueryUser() *UserQuery {
	return NewEntitlementEventClient(_m.config).QueryUser(_m)
}

// QueryGroup queries the "group" edge of the EntitlementEvent entity.
func (_m *EntitlementEvent) QueryGroup() *GroupQuery {
	return NewEntitlementEventClient(_m.config).QueryGroup(_m)
}

// QueryOrder queries the "order" edge of the EntitlementEvent entity.
func (_m *EntitlementEvent) QueryOrder() *PaymentOrderQuery {
	return NewEntitlementEventClient(_m.config).QueryOrder(_m)
}

// QueryRedeemCode queries the "redeem_code" edge of the EntitlementEvent entity.
func (_m *EntitlementEvent) QueryRedeemCode() *RedeemCodeQuery {
	return NewEntitlementEventClient(_m.config).QueryRedeemCode(_m)
}

// QueryActorUser queries the "actor_user" edge of the EntitlementEvent entity.
func (_m *EntitlementEvent) QueryActorUser() *UserQuery {
	return NewEntitlementEventClient(_m.config).QueryActorUser(_m)
}

// Update returns a builder for updating this EntitlementEvent.
// Note that you need to call EntitlementEvent.Unwrap() before calling this method if this EntitlementEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EntitlementEvent) Update() *EntitlementEventUpdateOne {
	return NewEntitlementEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EntitlementEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EntitlementEvent) Unwrap() *EntitlementEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntitlementEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EntitlementEvent) String() string {
	var builder strings.Builder
	builder.WriteString("EntitlementEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ValidityDays; v != nil {
		builder.WriteString("validity_days=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BalanceDelta; v != nil {
		builder.WriteString("balance_delta=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ConcurrencyDelta; v != nil {
		builder.WriteString("concurrency_delta=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OrderID; v != nil {
		builder.WriteString("order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RedeemCodeID; v != nil {
		builder.WriteString("redeem_code_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ActorUserID; v != nil {
		builder.WriteString("actor_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Note; v != nil {
		builder.WriteString("note=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// EntitlementEvents is a parsable slice of EntitlementEvent.
type EntitlementEvents []*EntitlementEvent
