// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/entitlementevent"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// EntitlementEventUpdate is the builder for updating EntitlementEvent entities.
type EntitlementEventUpdate struct {
	config
	hooks    []Hook
	mutation *EntitlementEventMutation
}

// Where appends a list predicates to the EntitlementEventUpdate builder.
func (_u *EntitlementEventUpdate) Where(ps ...predicate.EntitlementEvent) *EntitlementEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntitlementEventUpdate) SetUpdatedAt(v time.Time) *EntitlementEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EntitlementEventUpdate) SetDeletedAt(v time.Time) *EntitlementEventUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EntitlementEventUpdate) SetNillableDeletedAt(v *time.Time) *EntitlementEventUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EntitlementEventUpdate) ClearDeletedAt() *EntitlementEventUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EntitlementEventUpdate) SetUserID(v int64) *EntitlementEventUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EntitlementEventUpdate) SetNillableUserID(v *int64) *EntitlementEventUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *EntitlementEventUpdate) SetKind(v string) *EntitlementEventUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *EntitlementEventUpdate) SetNillableKind(v *string) *EntitlementEventUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *EntitlementEventUpdate) SetSource(v string) *EntitlementEventUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *EntitlementEventUpdate) SetNillableSource(v *string) *EntitlementEventUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *EntitlementEventUpdate) SetGroupID(v int64) *EntitlementEventUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *EntitlementEventUpdate) SetNillableGroupID(v *int64) *EntitlementEventUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *EntitlementEventUpdate) ClearGroupID() *EntitlementEventUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *EntitlementEventUpdate) SetValidityDays(v int) *EntitlementEventUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *EntitlementEventUpdate) SetNillableValidityDays(v *int) *EntitlementEventUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *EntitlementEventUpdate) AddValidityDays(v int) *EntitlementEventUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// ClearValidityDays clears the value of the "validity_days" field.
func (_u *EntitlementEventUpdate) ClearValidityDays() *EntitlementEventUpdate {
	_u.mutation.ClearValidityDays()
	return _u
}

// SetBalanceDelta sets the "balance_delta" field.
func (_u *EntitlementEventUpdate) SetBalanceDelta(v float64) *EntitlementEventUpdate {
	_u.mutation.ResetBalanceDelta()
	_u.mutation.SetBalanceDelta(v)
	return _u
}

// SetNillableBalanceDelta sets the "balance_delta" field if the given value is not nil.
func (_u *EntitlementEventUpdate) SetNillableBalanceDelta(v *float64) *EntitlementEventUpdate {
	if v != nil {
		_u.SetBalanceDelta(*v)
	}
	return _u
}

// AddBalanceDelta adds value to the "balance_delta" field.
func (_u *EntitlementEventUpdate) AddBalanceDelta(v float64) *EntitlementEventUpdate {
	_u.mutation.AddBalanceDelta(v)
	return _u
}

// ClearBalanceDelta clears the value of the "balance_delta" field.
func (_u *EntitlementEventUpdate) ClearBalanceDelta() *EntitlementEventUpdate {
	_u.mutation.ClearBalanceDelta()
	return _u
}

// SetConcurrencyDelta sets the "concurrency_delta" field.
func (_u *EntitlementEventUpdate) SetConcurrencyDelta(v int) *EntitlementEventUpdate {
	_u.mutation.ResetConcurrencyDelta()
	_u.mutation.SetConcurrencyDelta(v)
	return _u
}

// SetNillableConcurrencyDelta sets the "concurrency_delta" field if the given value is not nil.
func (_u *EntitlementEventUpdate) SetNillableConcurrencyDelta(v *int) *EntitlementEventUpdate {
	if v != nil {
		_u.SetConcurrencyDelta(*v)
	}
	return _u
}

// AddConcurrencyDelta adds value to the "concurrency_delta" field.
func (_u *EntitlementEventUpdate) AddConcurrencyDelta(v int) *EntitlementEventUpdate {
	_u.mutation.AddConcurrencyDelta(v)
	return _u
}

// ClearConcurrencyDelta clears the value of the "concurrency_delta" field.
func (_u *EntitlementEventUpdate) ClearConcurrencyDelta() *EntitlementEventUpdate {
	_u.mutation.ClearConcurrencyDelta()
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *EntitlementEventUpdate) SetOrderID(v int64) *EntitlementEventUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *EntitlementEventUpdate) SetNillableOrderID(v *int64) *EntitlementEventUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *EntitlementEventUpdate) ClearOrderID() *EntitlementEventUpdate {
	_u.mutation.ClearOrderID()
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *EntitlementEventUpdate) SetRedeemCodeID(v int64) *EntitlementEventUpdate {
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *EntitlementEventUpdate) SetNillableRedeemCodeID(v *int64) *EntitlementEventUpdate {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (_u *EntitlementEventUpdate) ClearRedeemCodeID() *EntitlementEventUpdate {
	_u.mutation.ClearRedeemCodeID()
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *EntitlementEventUpdate) SetActorUserID(v int64) *EntitlementEventUpdate {
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *EntitlementEventUpdate) SetNillableActorUserID(v *int64) *EntitlementEventUpdate {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *EntitlementEventUpdate) ClearActorUserID() *EntitlementEventUpdate {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetNote sets the "note" field.
func (_u *EntitlementEventUpdate) SetNote(v string) *EntitlementEventUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *EntitlementEventUpdate) SetNillableNote(v *string) *EntitlementEventUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *EntitlementEventUpdate) ClearNote() *EntitlementEventUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *EntitlementEventUpdate) SetUser(v *User) *EntitlementEventUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *EntitlementEventUpdate) SetGroup(v *Group) *EntitlementEventUpdate {
	return _u.SetGroupID(v.ID)
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_u *EntitlementEventUpdate) SetOrder(v *PaymentOrder) *EntitlementEventUpdate {
	return _u.SetOrderID(v.ID)
}

// SetRedeemCode sets the "redeem_code" edge to the RedeemCode entity.
func (_u *EntitlementEventUpdate) SetRedeemCode(v *RedeemCode) *EntitlementEventUpdate {
	return _u.SetRedeemCodeID(v.ID)
}

// SetActorUser sets the "actor_user" edge to the User entity.
func (_u *EntitlementEventUpdate) SetActorUser(v *User) *EntitlementEventUpdate {
	return _u.SetActorUserID(v.ID)
}

// Mutation returns the EntitlementEventMutation object of the builder.
func (_u *EntitlementEventUpdate) Mutation() *EntitlementEventMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *EntitlementEventUpdate) ClearUser() *EntitlementEventUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *EntitlementEventUpdate) ClearGroup() *EntitlementEventUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearOrder clears the "order" edge to the PaymentOrder entity.
func (_u *EntitlementEventUpdate) ClearOrder() *EntitlementEventUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// ClearRedeemCode clears the "redeem_code" edge to the RedeemCode entity.
func (_u *EntitlementEventUpdate) ClearRedeemCode() *EntitlementEventUpdate {
	_u.mutation.ClearRedeemCode()
	return _u
}

// ClearActorUser clears the "actor_user" edge to the User entity.
func (_u *EntitlementEventUpdate) ClearActorUser() *EntitlementEventUpdate {
	_u.mutation.ClearActorUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntitlementEventUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntitlementEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntitlementEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntitlementEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntitlementEventUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if entitlementevent.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized entitlementevent.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := entitlementevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntitlementEventUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := entitlementevent.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EntitlementEvent.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := entitlementevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "EntitlementEvent.source": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntitlementEvent.user"`)
	}
	return nil
}

func (_u *EntitlementEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entitlementevent.Table, entitlementevent.Columns, sqlgraph.NewFieldSpec(entitlementevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entitlementevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(entitlementevent.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(entitlementevent.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(entitlementevent.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(entitlementevent.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(entitlementevent.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(entitlementevent.FieldValidityDays, field.TypeInt, value)
	}
	if _u.mutation.ValidityDaysCleared() {
		_spec.ClearField(entitlementevent.FieldValidityDays, field.TypeInt)
	}
	if value, ok := _u.mutation.BalanceDelta(); ok {
		_spec.SetField(entitlementevent.FieldBalanceDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceDelta(); ok {
		_spec.AddField(entitlementevent.FieldBalanceDelta, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceDeltaCleared() {
		_spec.ClearField(entitlementevent.FieldBalanceDelta, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ConcurrencyDelta(); ok {
		_spec.SetField(entitlementevent.FieldConcurrencyDelta, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrencyDelta(); ok {
		_spec.AddField(entitlementevent.FieldConcurrencyDelta, field.TypeInt, value)
	}
	if _u.mutation.ConcurrencyDeltaCleared() {
		_spec.ClearField(entitlementevent.FieldConcurrencyDelta, field.TypeInt)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(entitlementevent.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(entitlementevent.FieldNote, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.UserTable,
			Columns: []string{entitlementevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.UserTable,
			Columns: []string{entitlementevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.GroupTable,
			Columns: []string{entitlementevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.GroupTable,
			Columns: []string{entitlementevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.OrderTable,
			Columns: []string{entitlementevent.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.OrderTable,
			Columns: []string{entitlementevent.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RedeemCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.RedeemCodeTable,
			Columns: []string{entitlementevent.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.RedeemCodeTable,
			Columns: []string{entitlementevent.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActorUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.ActorUserTable,
			Columns: []string{entitlementevent.ActorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.ActorUserTable,
			Columns: []string{entitlementevent.ActorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitlementevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntitlementEventUpdateOne is the builder for updating a single EntitlementEvent entity.
type EntitlementEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntitlementEventMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntitlementEventUpdateOne) SetUpdatedAt(v time.Time) *EntitlementEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EntitlementEventUpdateOne) SetDeletedAt(v time.Time) *EntitlementEventUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EntitlementEventUpdateOne) SetNillableDeletedAt(v *time.Time) *EntitlementEventUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EntitlementEventUpdateOne) ClearDeletedAt() *EntitlementEventUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EntitlementEventUpdateOne) SetUserID(v int64) *EntitlementEventUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EntitlementEventUpdateOne) SetNillableUserID(v *int64) *EntitlementEventUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *EntitlementEventUpdateOne) SetKind(v string) *EntitlementEventUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *EntitlementEventUpdateOne) SetNillableKind(v *string) *EntitlementEventUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *EntitlementEventUpdateOne) SetSource(v string) *EntitlementEventUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *EntitlementEventUpdateOne) SetNillableSource(v *string) *EntitlementEventUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *EntitlementEventUpdateOne) SetGroupID(v int64) *EntitlementEventUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *EntitlementEventUpdateOne) SetNillableGroupID(v *int64) *EntitlementEventUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *EntitlementEventUpdateOne) ClearGroupID() *EntitlementEventUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *EntitlementEventUpdateOne) SetValidityDays(v int) *EntitlementEventUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *EntitlementEventUpdateOne) SetNillableValidityDays(v *int) *EntitlementEventUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *EntitlementEventUpdateOne) AddValidityDays(v int) *EntitlementEventUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// ClearValidityDays clears the value of the "validity_days" field.
func (_u *EntitlementEventUpdateOne) ClearValidityDays() *EntitlementEventUpdateOne {
	_u.mutation.ClearValidityDays()
	return _u
}

// SetBalanceDelta sets the "balance_delta" field.
func (_u *EntitlementEventUpdateOne) SetBalanceDelta(v float64) *EntitlementEventUpdateOne {
	_u.mutation.ResetBalanceDelta()
	_u.mutation.SetBalanceDelta(v)
	return _u
}

// SetNillableBalanceDelta sets the "balance_delta" field if the given value is not nil.
func (_u *EntitlementEventUpdateOne) SetNillableBalanceDelta(v *float64) *EntitlementEventUpdateOne {
	if v != nil {
		_u.SetBalanceDelta(*v)
	}
	return _u
}

// AddBalanceDelta adds value to the "balance_delta" field.
func (_u *EntitlementEventUpdateOne) AddBalanceDelta(v float64) *EntitlementEventUpdateOne {
	_u.mutation.AddBalanceDelta(v)
	return _u
}

// ClearBalanceDelta clears the value of the "balance_delta" field.
func (_u *EntitlementEventUpdateOne) ClearBalanceDelta() *EntitlementEventUpdateOne {
	_u.mutation.ClearBalanceDelta()
	return _u
}

// SetConcurrencyDelta sets the "concurrency_delta" field.
func (_u *EntitlementEventUpdateOne) SetConcurrencyDelta(v int) *EntitlementEventUpdateOne {
	_u.mutation.ResetConcurrencyDelta()
	_u.mutation.SetConcurrencyDelta(v)
	return _u
}

// SetNillableConcurrencyDelta sets the "concurrency_delta" field if the given value is not nil.
func (_u *EntitlementEventUpdateOne) SetNillableConcurrencyDelta(v *int) *EntitlementEventUpdateOne {
	if v != nil {
		_u.SetConcurrencyDelta(*v)
	}
	return _u
}

// AddConcurrencyDelta adds value to the "concurrency_delta" field.
func (_u *EntitlementEventUpdateOne) AddConcurrencyDelta(v int) *EntitlementEventUpdateOne {
	_u.mutation.AddConcurrencyDelta(v)
	return _u
}

// ClearConcurrencyDelta clears the value of the "concurrency_delta" field.
func (_u *EntitlementEventUpdateOne) ClearConcurrencyDelta() *EntitlementEventUpdateOne {
	_u.mutation.ClearConcurrencyDelta()
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *EntitlementEventUpdateOne) SetOrderID(v int64) *EntitlementEventUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *EntitlementEventUpdateOne) SetNillableOrderID(v *int64) *EntitlementEventUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *EntitlementEventUpdateOne) ClearOrderID() *EntitlementEventUpdateOne {
	_u.mutation.ClearOrderID()
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *EntitlementEventUpdateOne) SetRedeemCodeID(v int64) *EntitlementEventUpdateOne {
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *EntitlementEventUpdateOne) SetNillableRedeemCodeID(v *int64) *EntitlementEventUpdateOne {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (_u *EntitlementEventUpdateOne) ClearRedeemCodeID() *EntitlementEventUpdateOne {
	_u.mutation.ClearRedeemCodeID()
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *EntitlementEventUpdateOne) SetActorUserID(v int64) *EntitlementEventUpdateOne {
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *EntitlementEventUpdateOne) SetNillableActorUserID(v *int64) *EntitlementEventUpdateOne {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *EntitlementEventUpdateOne) ClearActorUserID() *EntitlementEventUpdateOne {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetNote sets the "note" field.
func (_u *EntitlementEventUpdateOne) SetNote(v string) *EntitlementEventUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *EntitlementEventUpdateOne) SetNillableNote(v *string) *EntitlementEventUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *EntitlementEventUpdateOne) ClearNote() *EntitlementEventUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *EntitlementEventUpdateOne) SetUser(v *User) *EntitlementEventUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *EntitlementEventUpdateOne) SetGroup(v *Group) *EntitlementEventUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_u *EntitlementEventUpdateOne) SetOrder(v *PaymentOrder) *EntitlementEventUpdateOne {
	return _u.SetOrderID(v.ID)
}

// SetRedeemCode sets the "redeem_code" edge to the RedeemCode entity.
func (_u *EntitlementEventUpdateOne) SetRedeemCode(v *RedeemCode) *EntitlementEventUpdateOne {
	return _u.SetRedeemCodeID(v.ID)
}

// SetActorUser sets the "actor_user" edge to the User entity.
func (_u *EntitlementEventUpdateOne) SetActorUser(v *User) *EntitlementEventUpdateOne {
	return _u.SetActorUserID(v.ID)
}

// Mutation returns the EntitlementEventMutation object of the builder.
func (_u *EntitlementEventUpdateOne) Mutation() *EntitlementEventMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *EntitlementEventUpdateOne) ClearUser() *EntitlementEventUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *EntitlementEventUpdateOne) ClearGroup() *EntitlementEventUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearOrder clears the "order" edge to the PaymentOrder entity.
func (_u *EntitlementEventUpdateOne) ClearOrder() *EntitlementEventUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// ClearRedeemCode clears the "redeem_code" edge to the RedeemCode entity.
func (_u *EntitlementEventUpdateOne) ClearRedeemCode() *EntitlementEventUpdateOne {
	_u.mutation.ClearRedeemCode()
	return _u
}

// ClearActorUser clears the "actor_user" edge to the User entity.
func (_u *EntitlementEventUpdateOne) ClearActorUser() *EntitlementEventUpdateOne {
	_u.mutation.ClearActorUser()
	return _u
}

// Where appends a list predicates to the EntitlementEventUpdate builder.
func (_u *EntitlementEventUpdateOne) Where(ps ...predicate.EntitlementEvent) *EntitlementEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntitlementEventUpdateOne) Select(field string, fields ...string) *EntitlementEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EntitlementEvent entity.
func (_u *EntitlementEventUpdateOne) Save(ctx context.Context) (*EntitlementEvent, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntitlementEventUpdateOne) SaveX(ctx context.Context) *EntitlementEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntitlementEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntitlementEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntitlementEventUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if entitlementevent.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized entitlementevent.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := entitlementevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntitlementEventUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := entitlementevent.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EntitlementEvent.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := entitlementevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "EntitlementEvent.source": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntitlementEvent.user"`)
	}
	return nil
}

func (_u *EntitlementEventUpdateOne) sqlSave(ctx context.Context) (_node *EntitlementEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entitlementevent.Table, entitlementevent.Columns, sqlgraph.NewFieldSpec(entitlementevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EntitlementEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entitlementevent.FieldID)
		for _, f := range fields {
			if !entitlementevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entitlementevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entitlementevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(entitlementevent.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(entitlementevent.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(entitlementevent.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(entitlementevent.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(entitlementevent.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(entitlementevent.FieldValidityDays, field.TypeInt, value)
	}
	if _u.mutation.ValidityDaysCleared() {
		_spec.ClearField(entitlementevent.FieldValidityDays, field.TypeInt)
	}
	if value, ok := _u.mutation.BalanceDelta(); ok {
		_spec.SetField(entitlementevent.FieldBalanceDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceDelta(); ok {
		_spec.AddField(entitlementevent.FieldBalanceDelta, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceDeltaCleared() {
		_spec.ClearField(entitlementevent.FieldBalanceDelta, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ConcurrencyDelta(); ok {
		_spec.SetField(entitlementevent.FieldConcurrencyDelta, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrencyDelta(); ok {
		_spec.AddField(entitlementevent.FieldConcurrencyDelta, field.TypeInt, value)
	}
	if _u.mutation.ConcurrencyDeltaCleared() {
		_spec.ClearField(entitlementevent.FieldConcurrencyDelta, field.TypeInt)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(entitlementevent.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(entitlementevent.FieldNote, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.UserTable,
			Columns: []string{entitlementevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.UserTable,
			Columns: []string{entitlementevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.GroupTable,
			Columns: []string{entitlementevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.GroupTable,
			Columns: []string{entitlementevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.OrderTable,
			Columns: []string{entitlementevent.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.OrderTable,
			Columns: []string{entitlementevent.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RedeemCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.RedeemCodeTable,
			Columns: []string{entitlementevent.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.RedeemCodeTable,
			Columns: []string{entitlementevent.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActorUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.ActorUserTable,
			Columns: []string{entitlementevent.ActorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.ActorUserTable,
			Columns: []string{entitlementevent.ActorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EntitlementEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitlementevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
