// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/entitlementevent"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// EntitlementEventCreate is the builder for creating a EntitlementEvent entity.
type EntitlementEventCreate struct {
	config
	mutation *EntitlementEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EntitlementEventCreate) SetCreatedAt(v time.Time) *EntitlementEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EntitlementEventCreate) SetNillableCreatedAt(v *time.Time) *EntitlementEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EntitlementEventCreate) SetUpdatedAt(v time.Time) *EntitlementEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EntitlementEventCreate) SetNillableUpdatedAt(v *time.Time) *EntitlementEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *EntitlementEventCreate) SetDeletedAt(v time.Time) *EntitlementEventCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *EntitlementEventCreate) SetNillableDeletedAt(v *time.Time) *EntitlementEventCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *EntitlementEventCreate) SetUserID(v int64) *EntitlementEventCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *EntitlementEventCreate) SetKind(v string) *EntitlementEventCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *EntitlementEventCreate) SetSource(v string) *EntitlementEventCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *EntitlementEventCreate) SetGroupID(v int64) *EntitlementEventCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *EntitlementEventCreate) SetNillableGroupID(v *int64) *EntitlementEventCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *EntitlementEventCreate) SetValidityDays(v int) *EntitlementEventCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_c *EntitlementEventCreate) SetNillableValidityDays(v *int) *EntitlementEventCreate {
	if v != nil {
		_c.SetValidityDays(*v)
	}
	return _c
}

// SetBalanceDelta sets the "balance_delta" field.
func (_c *EntitlementEventCreate) SetBalanceDelta(v float64) *EntitlementEventCreate {
	_c.mutation.SetBalanceDelta(v)
	return _c
}

// SetNillableBalanceDelta sets the "balance_delta" field if the given value is not nil.
func (_c *EntitlementEventCreate) SetNillableBalanceDelta(v *float64) *EntitlementEventCreate {
	if v != nil {
		_c.SetBalanceDelta(*v)
	}
	return _c
}

// SetConcurrencyDelta sets the "concurrency_delta" field.
func (_c *EntitlementEventCreate) SetConcurrencyDelta(v int) *EntitlementEventCreate {
	_c.mutation.SetConcurrencyDelta(v)
	return _c
}

// SetNillableConcurrencyDelta sets the "concurrency_delta" field if the given value is not nil.
func (_c *EntitlementEventCreate) SetNillableConcurrencyDelta(v *int) *EntitlementEventCreate {
	if v != nil {
		_c.SetConcurrencyDelta(*v)
	}
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *EntitlementEventCreate) SetOrderID(v int64) *EntitlementEventCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_c *EntitlementEventCreate) SetNillableOrderID(v *int64) *EntitlementEventCreate {
	if v != nil {
		_c.SetOrderID(*v)
	}
	return _c
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_c *EntitlementEventCreate) SetRedeemCodeID(v int64) *EntitlementEventCreate {
	_c.mutation.SetRedeemCodeID(v)
	return _c
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_c *EntitlementEventCreate) SetNillableRedeemCodeID(v *int64) *EntitlementEventCreate {
	if v != nil {
		_c.SetRedeemCodeID(*v)
	}
	return _c
}

// SetActorUserID sets the "actor_user_id" field.
func (_c *EntitlementEventCreate) SetActorUserID(v int64) *EntitlementEventCreate {
	_c.mutation.SetActorUserID(v)
	return _c
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_c *EntitlementEventCreate) SetNillableActorUserID(v *int64) *EntitlementEventCreate {
	if v != nil {
		_c.SetActorUserID(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *EntitlementEventCreate) SetNote(v string) *EntitlementEventCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *EntitlementEventCreate) SetNillableNote(v *string) *EntitlementEventCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *EntitlementEventCreate) SetUser(v *User) *EntitlementEventCreate {
	return _c.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *EntitlementEventCreate) SetGroup(v *Group) *EntitlementEventCreate {
	return _c.SetGroupID(v.ID)
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_c *EntitlementEventCreate) SetOrder(v *PaymentOrder) *EntitlementEventCreate {
	return _c.SetOrderID(v.ID)
}

// SetRedeemCode sets the "redeem_code" edge to the RedeemCode entity.
func (_c *EntitlementEventCreate) SetRedeemCode(v *RedeemCode) *EntitlementEventCreate {
	return _c.SetRedeemCodeID(v.ID)
}

// SetActorUser sets the "actor_user" edge to the User entity.
func (_c *EntitlementEventCreate) SetActorUser(v *User) *EntitlementEventCreate {
	return _c.SetActorUserID(v.ID)
}

// Mutation returns the EntitlementEventMutation object of the builder.
func (_c *EntitlementEventCreate) Mutation() *EntitlementEventMutation {
	return _c.mutation
}

// Save creates the EntitlementEvent in the database.
func (_c *EntitlementEventCreate) Save(ctx context.Context) (*EntitlementEvent, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntitlementEventCreate) SaveX(ctx context.Context) *EntitlementEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntitlementEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntitlementEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EntitlementEventCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if entitlementevent.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized entitlementevent.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := entitlementevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if entitlementevent.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized entitlementevent.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := entitlementevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntitlementEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EntitlementEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EntitlementEvent.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "EntitlementEvent.user_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "EntitlementEvent.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := entitlementevent.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EntitlementEvent.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "EntitlementEvent.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := entitlementevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "EntitlementEvent.source": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "EntitlementEvent.user"`)}
	}
	return nil
}

func (_c *EntitlementEventCreate) sqlSave(ctx context.Context) (*EntitlementEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntitlementEventCreate) createSpec() (*EntitlementEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &EntitlementEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entitlementevent.Table, sqlgraph.NewFieldSpec(entitlementevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(entitlementevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(entitlementevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(entitlementevent.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(entitlementevent.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(entitlementevent.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(entitlementevent.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = &value
	}
	if value, ok := _c.mutation.BalanceDelta(); ok {
		_spec.SetField(entitlementevent.FieldBalanceDelta, field.TypeFloat64, value)
		_node.BalanceDelta = &value
	}
	if value, ok := _c.mutation.ConcurrencyDelta(); ok {
		_spec.SetField(entitlementevent.FieldConcurrencyDelta, field.TypeInt, value)
		_node.ConcurrencyDelta = &value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(entitlementevent.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.UserTable,
			Columns: []string{entitlementevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.GroupTable,
			Columns: []string{entitlementevent.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.OrderTable,
			Columns: []string{entitlementevent.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RedeemCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.RedeemCodeTable,
			Columns: []string{entitlementevent.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RedeemCodeID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ActorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitlementevent.ActorUserTable,
			Columns: []string{entitlementevent.ActorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ActorUserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EntitlementEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EntitlementEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EntitlementEventCreate) OnConflict(opts ...sql.ConflictOption) *EntitlementEventUpsertOne {
	_c.conflict = opts
	return &EntitlementEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EntitlementEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EntitlementEventCreate) OnConflictColumns(columns ...string) *EntitlementEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EntitlementEventUpsertOne{
		create: _c,
	}
}

type (
	// EntitlementEventUpsertOne is the builder for "upsert"-ing
	//  one EntitlementEvent node.
	EntitlementEventUpsertOne struct {
		create *EntitlementEventCreate
	}

	// EntitlementEventUpsert is the "OnConflict" setter.
	EntitlementEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EntitlementEventUpsert) SetUpdatedAt(v time.Time) *EntitlementEventUpsert {
	u.Set(entitlementevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EntitlementEventUpsert) UpdateUpdatedAt() *EntitlementEventUpsert {
	u.SetExcluded(entitlementevent.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EntitlementEventUpsert) SetDeletedAt(v time.Time) *EntitlementEventUpsert {
	u.Set(entitlementevent.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EntitlementEventUpsert) UpdateDeletedAt() *EntitlementEventUpsert {
	u.SetExcluded(entitlementevent.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EntitlementEventUpsert) ClearDeletedAt() *EntitlementEventUpsert {
	u.SetNull(entitlementevent.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *EntitlementEventUpsert) SetUserID(v int64) *EntitlementEventUpsert {
	u.Set(entitlementevent.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EntitlementEventUpsert) UpdateUserID() *EntitlementEventUpsert {
	u.SetExcluded(entitlementevent.FieldUserID)
	return u
}

// SetKind sets the "kind" field.
func (u *EntitlementEventUpsert) SetKind(v string) *EntitlementEventUpsert {
	u.Set(entitlementevent.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EntitlementEventUpsert) UpdateKind() *EntitlementEventUpsert {
	u.SetExcluded(entitlementevent.FieldKind)
	return u
}

// SetSource sets the "source" field.
func (u *EntitlementEventUpsert) SetSource(v string) *EntitlementEventUpsert {
	u.Set(entitlementevent.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *EntitlementEventUpsert) UpdateSource() *EntitlementEventUpsert {
	u.SetExcluded(entitlementevent.FieldSource)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *EntitlementEventUpsert) SetGroupID(v int64) *EntitlementEventUpsert {
	u.Set(entitlementevent.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EntitlementEventUpsert) UpdateGroupID() *EntitlementEventUpsert {
	u.SetExcluded(entitlementevent.FieldGroupID)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *EntitlementEventUpsert) ClearGroupID() *EntitlementEventUpsert {
	u.SetNull(entitlementevent.FieldGroupID)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *EntitlementEventUpsert) SetValidityDays(v int) *EntitlementEventUpsert {
	u.Set(entitlementevent.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *EntitlementEventUpsert) UpdateValidityDays() *EntitlementEventUpsert {
	u.SetExcluded(entitlementevent.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *EntitlementEventUpsert) AddValidityDays(v int) *EntitlementEventUpsert {
	u.Add(entitlementevent.FieldValidityDays, v)
	return u
}

// ClearValidityDays clears the value of the "validity_days" field.
func (u *EntitlementEventUpsert) ClearValidityDays() *EntitlementEventUpsert {
	u.SetNull(entitlementevent.FieldValidityDays)
	return u
}

// SetBalanceDelta sets the "balance_delta" field.
func (u *EntitlementEventUpsert) SetBalanceDelta(v float64) *EntitlementEventUpsert {
	u.Set(entitlementevent.FieldBalanceDelta, v)
	return u
}

// UpdateBalanceDelta sets the "balance_delta" field to the value that was provided on create.
func (u *EntitlementEventUpsert) UpdateBalanceDelta() *EntitlementEventUpsert {
	u.SetExcluded(entitlementevent.FieldBalanceDelta)
	return u
}

// AddBalanceDelta adds v to the "balance_delta" field.
func (u *EntitlementEventUpsert) AddBalanceDelta(v float64) *EntitlementEventUpsert {
	u.Add(entitlementevent.FieldBalanceDelta, v)
	return u
}

// ClearBalanceDelta clears the value of the "balance_delta" field.
func (u *EntitlementEventUpsert) ClearBalanceDelta() *EntitlementEventUpsert {
	u.SetNull(entitlementevent.FieldBalanceDelta)
	return u
}

// SetConcurrencyDelta sets the "concurrency_delta" field.
func (u *EntitlementEventUpsert) SetConcurrencyDelta(v int) *EntitlementEventUpsert {
	u.Set(entitlementevent.FieldConcurrencyDelta, v)
	return u
}

// UpdateConcurrencyDelta sets the "concurrency_delta" field to the value that was provided on create.
func (u *EntitlementEventUpsert) UpdateConcurrencyDelta() *EntitlementEventUpsert {
	u.SetExcluded(entitlementevent.FieldConcurrencyDelta)
	return u
}

// AddConcurrencyDelta adds v to the "concurrency_delta" field.
func (u *EntitlementEventUpsert) AddConcurrencyDelta(v int) *EntitlementEventUpsert {
	u.Add(entitlementevent.FieldConcurrencyDelta, v)
	return u
}

// ClearConcurrencyDelta clears the value of the "concurrency_delta" field.
func (u *EntitlementEventUpsert) ClearConcurrencyDelta() *EntitlementEventUpsert {
	u.SetNull(entitlementevent.FieldConcurrencyDelta)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *EntitlementEventUpsert) SetOrderID(v int64) *EntitlementEventUpsert {
	u.Set(entitlementevent.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *EntitlementEventUpsert) UpdateOrderID() *EntitlementEventUpsert {
	u.SetExcluded(entitlementevent.FieldOrderID)
	return u
}

// ClearOrderID clears the value of the "order_id" field.
func (u *EntitlementEventUpsert) ClearOrderID() *EntitlementEventUpsert {
	u.SetNull(entitlementevent.FieldOrderID)
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *EntitlementEventUpsert) SetRedeemCodeID(v int64) *EntitlementEventUpsert {
	u.Set(entitlementevent.FieldRedeemCodeID, v)
	return u
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *EntitlementEventUpsert) UpdateRedeemCodeID() *EntitlementEventUpsert {
	u.SetExcluded(entitlementevent.FieldRedeemCodeID)
	return u
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *EntitlementEventUpsert) ClearRedeemCodeID() *EntitlementEventUpsert {
	u.SetNull(entitlementevent.FieldRedeemCodeID)
	return u
}

// SetActorUserID sets the "actor_user_id" field.
func (u *EntitlementEventUpsert) SetActorUserID(v int64) *EntitlementEventUpsert {
	u.Set(entitlementevent.FieldActorUserID, v)
	return u
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *EntitlementEventUpsert) UpdateActorUserID() *EntitlementEventUpsert {
	u.SetExcluded(entitlementevent.FieldActorUserID)
	return u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (u *EntitlementEventUpsert) ClearActorUserID() *EntitlementEventUpsert {
	u.SetNull(entitlementevent.FieldActorUserID)
	return u
}

// SetNote sets the "note" field.
func (u *EntitlementEventUpsert) SetNote(v string) *EntitlementEventUpsert {
	u.Set(entitlementevent.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *EntitlementEventUpsert) UpdateNote() *EntitlementEventUpsert {
	u.SetExcluded(entitlementevent.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *EntitlementEventUpsert) ClearNote() *EntitlementEventUpsert {
	u.SetNull(entitlementevent.FieldNote)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EntitlementEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EntitlementEventUpsertOne) UpdateNewValues() *EntitlementEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(entitlementevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EntitlementEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EntitlementEventUpsertOne) Ignore() *EntitlementEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EntitlementEventUpsertOne) DoNothing() *EntitlementEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EntitlementEventCreate.OnConflict
// documentation for more info.
func (u *EntitlementEventUpsertOne) Update(set func(*EntitlementEventUpsert)) *EntitlementEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EntitlementEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EntitlementEventUpsertOne) SetUpdatedAt(v time.Time) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EntitlementEventUpsertOne) UpdateUpdatedAt() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EntitlementEventUpsertOne) SetDeletedAt(v time.Time) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EntitlementEventUpsertOne) UpdateDeletedAt() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EntitlementEventUpsertOne) ClearDeletedAt() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *EntitlementEventUpsertOne) SetUserID(v int64) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EntitlementEventUpsertOne) UpdateUserID() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateUserID()
	})
}

// SetKind sets the "kind" field.
func (u *EntitlementEventUpsertOne) SetKind(v string) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EntitlementEventUpsertOne) UpdateKind() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateKind()
	})
}

// SetSource sets the "source" field.
func (u *EntitlementEventUpsertOne) SetSource(v string) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *EntitlementEventUpsertOne) UpdateSource() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateSource()
	})
}

// SetGroupID sets the "group_id" field.
func (u *EntitlementEventUpsertOne) SetGroupID(v int64) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EntitlementEventUpsertOne) UpdateGroupID() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *EntitlementEventUpsertOne) ClearGroupID() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearGroupID()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *EntitlementEventUpsertOne) SetValidityDays(v int) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *EntitlementEventUpsertOne) AddValidityDays(v int) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *EntitlementEventUpsertOne) UpdateValidityDays() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateValidityDays()
	})
}

// ClearValidityDays clears the value of the "validity_days" field.
func (u *EntitlementEventUpsertOne) ClearValidityDays() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearValidityDays()
	})
}

// SetBalanceDelta sets the "balance_delta" field.
func (u *EntitlementEventUpsertOne) SetBalanceDelta(v float64) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetBalanceDelta(v)
	})
}

// AddBalanceDelta adds v to the "balance_delta" field.
func (u *EntitlementEventUpsertOne) AddBalanceDelta(v float64) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.AddBalanceDelta(v)
	})
}

// UpdateBalanceDelta sets the "balance_delta" field to the value that was provided on create.
func (u *EntitlementEventUpsertOne) UpdateBalanceDelta() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateBalanceDelta()
	})
}

// ClearBalanceDelta clears the value of the "balance_delta" field.
func (u *EntitlementEventUpsertOne) ClearBalanceDelta() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearBalanceDelta()
	})
}

// SetConcurrencyDelta sets the "concurrency_delta" field.
func (u *EntitlementEventUpsertOne) SetConcurrencyDelta(v int) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetConcurrencyDelta(v)
	})
}

// AddConcurrencyDelta adds v to the "concurrency_delta" field.
func (u *EntitlementEventUpsertOne) AddConcurrencyDelta(v int) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.AddConcurrencyDelta(v)
	})
}

// UpdateConcurrencyDelta sets the "concurrency_delta" field to the value that was provided on create.
func (u *EntitlementEventUpsertOne) UpdateConcurrencyDelta() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateConcurrencyDelta()
	})
}

// ClearConcurrencyDelta clears the value of the "concurrency_delta" field.
func (u *EntitlementEventUpsertOne) ClearConcurrencyDelta() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearConcurrencyDelta()
	})
}

// SetOrderID sets the "order_id" field.
func (u *EntitlementEventUpsertOne) SetOrderID(v int64) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *EntitlementEventUpsertOne) UpdateOrderID() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *EntitlementEventUpsertOne) ClearOrderID() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearOrderID()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *EntitlementEventUpsertOne) SetRedeemCodeID(v int64) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *EntitlementEventUpsertOne) UpdateRedeemCodeID() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *EntitlementEventUpsertOne) ClearRedeemCodeID() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearRedeemCodeID()
	})
}

// SetActorUserID sets the "actor_user_id" field.
func (u *EntitlementEventUpsertOne) SetActorUserID(v int64) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetActorUserID(v)
	})
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *EntitlementEventUpsertOne) UpdateActorUserID() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateActorUserID()
	})
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (u *EntitlementEventUpsertOne) ClearActorUserID() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearActorUserID()
	})
}

// SetNote sets the "note" field.
func (u *EntitlementEventUpsertOne) SetNote(v string) *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *EntitlementEventUpsertOne) UpdateNote() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *EntitlementEventUpsertOne) ClearNote() *EntitlementEventUpsertOne {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *EntitlementEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EntitlementEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EntitlementEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EntitlementEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EntitlementEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EntitlementEventCreateBulk is the builder for creating many EntitlementEvent entities in bulk.
type EntitlementEventCreateBulk struct {
	config
	err      error
	builders []*EntitlementEventCreate
	conflict []sql.ConflictOption
}

// Save creates the EntitlementEvent entities in the database.
func (_c *EntitlementEventCreateBulk) Save(ctx context.Context) ([]*EntitlementEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EntitlementEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntitlementEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntitlementEventCreateBulk) SaveX(ctx context.Context) []*EntitlementEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntitlementEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntitlementEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EntitlementEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EntitlementEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EntitlementEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *EntitlementEventUpsertBulk {
	_c.conflict = opts
	return &EntitlementEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EntitlementEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EntitlementEventCreateBulk) OnConflictColumns(columns ...string) *EntitlementEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EntitlementEventUpsertBulk{
		create: _c,
	}
}

// EntitlementEventUpsertBulk is the builder for "upsert"-ing
// a bulk of EntitlementEvent nodes.
type EntitlementEventUpsertBulk struct {
	create *EntitlementEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EntitlementEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EntitlementEventUpsertBulk) UpdateNewValues() *EntitlementEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(entitlementevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EntitlementEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EntitlementEventUpsertBulk) Ignore() *EntitlementEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EntitlementEventUpsertBulk) DoNothing() *EntitlementEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EntitlementEventCreateBulk.OnConflict
// documentation for more info.
func (u *EntitlementEventUpsertBulk) Update(set func(*EntitlementEventUpsert)) *EntitlementEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EntitlementEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EntitlementEventUpsertBulk) SetUpdatedAt(v time.Time) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EntitlementEventUpsertBulk) UpdateUpdatedAt() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EntitlementEventUpsertBulk) SetDeletedAt(v time.Time) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EntitlementEventUpsertBulk) UpdateDeletedAt() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EntitlementEventUpsertBulk) ClearDeletedAt() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *EntitlementEventUpsertBulk) SetUserID(v int64) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EntitlementEventUpsertBulk) UpdateUserID() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateUserID()
	})
}

// SetKind sets the "kind" field.
func (u *EntitlementEventUpsertBulk) SetKind(v string) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EntitlementEventUpsertBulk) UpdateKind() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateKind()
	})
}

// SetSource sets the "source" field.
func (u *EntitlementEventUpsertBulk) SetSource(v string) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *EntitlementEventUpsertBulk) UpdateSource() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateSource()
	})
}

// SetGroupID sets the "group_id" field.
func (u *EntitlementEventUpsertBulk) SetGroupID(v int64) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EntitlementEventUpsertBulk) UpdateGroupID() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *EntitlementEventUpsertBulk) ClearGroupID() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearGroupID()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *EntitlementEventUpsertBulk) SetValidityDays(v int) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *EntitlementEventUpsertBulk) AddValidityDays(v int) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *EntitlementEventUpsertBulk) UpdateValidityDays() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateValidityDays()
	})
}

// ClearValidityDays clears the value of the "validity_days" field.
func (u *EntitlementEventUpsertBulk) ClearValidityDays() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearValidityDays()
	})
}

// SetBalanceDelta sets the "balance_delta" field.
func (u *EntitlementEventUpsertBulk) SetBalanceDelta(v float64) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetBalanceDelta(v)
	})
}

// AddBalanceDelta adds v to the "balance_delta" field.
func (u *EntitlementEventUpsertBulk) AddBalanceDelta(v float64) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.AddBalanceDelta(v)
	})
}

// UpdateBalanceDelta sets the "balance_delta" field to the value that was provided on create.
func (u *EntitlementEventUpsertBulk) UpdateBalanceDelta() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateBalanceDelta()
	})
}

// ClearBalanceDelta clears the value of the "balance_delta" field.
func (u *EntitlementEventUpsertBulk) ClearBalanceDelta() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearBalanceDelta()
	})
}

// SetConcurrencyDelta sets the "concurrency_delta" field.
func (u *EntitlementEventUpsertBulk) SetConcurrencyDelta(v int) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetConcurrencyDelta(v)
	})
}

// AddConcurrencyDelta adds v to the "concurrency_delta" field.
func (u *EntitlementEventUpsertBulk) AddConcurrencyDelta(v int) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.AddConcurrencyDelta(v)
	})
}

// UpdateConcurrencyDelta sets the "concurrency_delta" field to the value that was provided on create.
func (u *EntitlementEventUpsertBulk) UpdateConcurrencyDelta() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateConcurrencyDelta()
	})
}

// ClearConcurrencyDelta clears the value of the "concurrency_delta" field.
func (u *EntitlementEventUpsertBulk) ClearConcurrencyDelta() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearConcurrencyDelta()
	})
}

// SetOrderID sets the "order_id" field.
func (u *EntitlementEventUpsertBulk) SetOrderID(v int64) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *EntitlementEventUpsertBulk) UpdateOrderID() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *EntitlementEventUpsertBulk) ClearOrderID() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearOrderID()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *EntitlementEventUpsertBulk) SetRedeemCodeID(v int64) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *EntitlementEventUpsertBulk) UpdateRedeemCodeID() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *EntitlementEventUpsertBulk) ClearRedeemCodeID() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearRedeemCodeID()
	})
}

// SetActorUserID sets the "actor_user_id" field.
func (u *EntitlementEventUpsertBulk) SetActorUserID(v int64) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetActorUserID(v)
	})
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *EntitlementEventUpsertBulk) UpdateActorUserID() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateActorUserID()
	})
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (u *EntitlementEventUpsertBulk) ClearActorUserID() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearActorUserID()
	})
}

// SetNote sets the "note" field.
func (u *EntitlementEventUpsertBulk) SetNote(v string) *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *EntitlementEventUpsertBulk) UpdateNote() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *EntitlementEventUpsertBulk) ClearNote() *EntitlementEventUpsertBulk {
	return u.Update(func(s *EntitlementEventUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *EntitlementEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EntitlementEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EntitlementEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EntitlementEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
