// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/paymentproduct"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentOrder is the model entity for the PaymentOrder schema.
type PaymentOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// OrderNo holds the value of the "order_no" field.
	OrderNo string `json:"order_no,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// subscription | balance
	Kind string `json:"kind,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID *int64 `json:"product_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// AmountCents holds the value of the "amount_cents" field.
	AmountCents int64 `json:"amount_cents,omitempty"`
	// ClientRequestID holds the value of the "client_request_id" field.
	ClientRequestID *string `json:"client_request_id,omitempty"`
	// ProviderTradeNo holds the value of the "provider_trade_no" field.
	ProviderTradeNo *string `json:"provider_trade_no,omitempty"`
	// PayURL holds the value of the "pay_url" field.
	PayURL *string `json:"pay_url,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// FulfilledAt holds the value of the "fulfilled_at" field.
	FulfilledAt *time.Time `json:"fulfilled_at,omitempty"`
	// GrantGroupID holds the value of the "grant_group_id" field.
	GrantGroupID *int64 `json:"grant_group_id,omitempty"`
	// GrantValidityDays holds the value of the "grant_validity_days" field.
	GrantValidityDays *int `json:"grant_validity_days,omitempty"`
	// GrantCreditBalance holds the value of the "grant_credit_balance" field.
	GrantCreditBalance *float64 `json:"grant_credit_balance,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentOrderQuery when eager-loading is set.
	Edges        PaymentOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PaymentOrderEdges holds the relations/edges for other nodes in the graph.
type PaymentOrderEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Product holds the value of the product edge.
	Product *PaymentProduct `json:"product,omitempty"`
	// GrantGroup holds the value of the grant_group edge.
	GrantGroup *Group `json:"grant_group,omitempty"`
	// EntitlementEvents holds the value of the entitlement_events edge.
	EntitlementEvents []*EntitlementEvent `json:"entitlement_events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentOrderEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentOrderEdges) ProductOrErr() (*PaymentProduct, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: paymentproduct.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// GrantGroupOrErr returns the GrantGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentOrderEdges) GrantGroupOrErr() (*Group, error) {
	if e.GrantGroup != nil {
		return e.GrantGroup, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "grant_group"}
}

// EntitlementEventsOrErr returns the EntitlementEvents value or an error if the edge
// was not loaded in eager-loading.
func (e PaymentOrderEdges) EntitlementEventsOrErr() ([]*EntitlementEvent, error) {
	if e.loadedTypes[3] {
		return e.EntitlementEvents, nil
	}
	return nil, &NotLoadedError{edge: "entitlement_events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentorder.FieldGrantCreditBalance:
			values[i] = new(sql.NullFloat64)
		case paymentorder.FieldID, paymentorder.FieldUserID, paymentorder.FieldProductID, paymentorder.FieldAmountCents, paymentorder.FieldGrantGroupID, paymentorder.FieldGrantValidityDays:
			values[i] = new(sql.NullInt64)
		case paymentorder.FieldOrderNo, paymentorder.FieldKind, paymentorder.FieldStatus, paymentorder.FieldProvider, paymentorder.FieldCurrency, paymentorder.FieldClientRequestID, paymentorder.FieldProviderTradeNo, paymentorder.FieldPayURL, paymentorder.FieldNotes:
			values[i] = new(sql.NullString)
		case paymentorder.FieldCreatedAt, paymentorder.FieldUpdatedAt, paymentorder.FieldExpiresAt, paymentorder.FieldPaidAt, paymentorder.FieldFulfilledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentOrder fields.
func (_m *PaymentOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case paymentorder.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = value.String
			}
		case paymentorder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case paymentorder.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case paymentorder.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = new(int64)
				*_m.ProductID = value.Int64
			}
		case paymentorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case paymentorder.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case paymentorder.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case paymentorder.FieldAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cents", values[i])
			} else if value.Valid {
				_m.AmountCents = value.Int64
			}
		case paymentorder.FieldClientRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_request_id", values[i])
			} else if value.Valid {
				_m.ClientRequestID = new(string)
				*_m.ClientRequestID = value.String
			}
		case paymentorder.FieldProviderTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_trade_no", values[i])
			} else if value.Valid {
				_m.ProviderTradeNo = new(string)
				*_m.ProviderTradeNo = value.String
			}
		case paymentorder.FieldPayURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pay_url", values[i])
			} else if value.Valid {
				_m.PayURL = new(string)
				*_m.PayURL = value.String
			}
		case paymentorder.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case paymentorder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case paymentorder.FieldFulfilledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fulfilled_at", values[i])
			} else if value.Valid {
				_m.FulfilledAt = new(time.Time)
				*_m.FulfilledAt = value.Time
			}
		case paymentorder.FieldGrantGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grant_group_id", values[i])
			} else if value.Valid {
				_m.GrantGroupID = new(int64)
				*_m.GrantGroupID = value.Int64
			}
		case paymentorder.FieldGrantValidityDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grant_validity_days", values[i])
			} else if value.Valid {
				_m.GrantValidityDays = new(int)
				*_m.GrantValidityDays = int(value.Int64)
			}
		case paymentorder.FieldGrantCreditBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field grant_credit_balance", values[i])
			} else if value.Valid {
				_m.GrantCreditBalance = new(float64)
				*_m.GrantCreditBalance = value.Float64
			}
		case paymentorder.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentOrder.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PaymentOrder entity.
func (_m *PaymentOrder) QueryUser() *UserQuery {
	return NewPaymentOrderClient(_m.config).QueryUser(_m)
}

// QueryProduct queries the "product" edge of the PaymentOrder entity.
func (_m *PaymentOrder) QueryProduct() *PaymentProductQuery {
	return NewPaymentOrderClient(_m.config).QueryProduct(_m)
}

// QueryGrantGroup queries the "grant_group" edge of the PaymentOrder entity.
func (_m *PaymentOrder) QueryGrantGroup() *GroupQuery {
	return NewPaymentOrderClient(_m.config).QueryGrantGroup(_m)
}

// QueryEntitlementEvents queries the "entitlement_events" edge of the PaymentOrder entity.
func (_m *PaymentOrder) QueryEntitlementEvents() *EntitlementEventQuery {
	return NewPaymentOrderClient(_m.config).QueryEntitlementEvents(_m)
}

// Update returns a builder for updating this PaymentOrder.
// Note that you need to call PaymentOrder.Unwrap() before calling this method if this PaymentOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentOrder) Update() *PaymentOrderUpdateOne {
	return NewPaymentOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentOrder) Unwrap() *PaymentOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentOrder) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("order_no=")
	builder.WriteString(_m.OrderNo)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	if v := _m.ProductID; v != nil {
		builder.WriteString("product_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("amount_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCents))
	builder.WriteString(", ")
	if v := _m.ClientRequestID; v != nil {
		builder.WriteString("client_request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProviderTradeNo; v != nil {
		builder.WriteString("provider_trade_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PayURL; v != nil {
		builder.WriteString("pay_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FulfilledAt; v != nil {
		builder.WriteString("fulfilled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.GrantGroupID; v != nil {
		builder.WriteString("grant_group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GrantValidityDays; v != nil {
		builder.WriteString("grant_validity_days=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GrantCreditBalance; v != nil {
		builder.WriteString("grant_credit_balance=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// PaymentOrders is a parsable slice of PaymentOrder.
type PaymentOrders []*PaymentOrder
