// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/paymentproduct"
)

// PaymentProduct is the model entity for the PaymentProduct schema.
type PaymentProduct struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// subscription | balance
	Kind string `json:"kind,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// DescriptionMd holds the value of the "description_md" field.
	DescriptionMd string `json:"description_md,omitempty"`
	// active | inactive
	Status string `json:"status,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// PriceCents holds the value of the "price_cents" field.
	PriceCents int64 `json:"price_cents,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// ValidityDays holds the value of the "validity_days" field.
	ValidityDays *int `json:"validity_days,omitempty"`
	// CreditBalance holds the value of the "credit_balance" field.
	CreditBalance *float64 `json:"credit_balance,omitempty"`
	// AllowCustomAmount holds the value of the "allow_custom_amount" field.
	AllowCustomAmount bool `json:"allow_custom_amount,omitempty"`
	// MinAmountCents holds the value of the "min_amount_cents" field.
	MinAmountCents *int64 `json:"min_amount_cents,omitempty"`
	// MaxAmountCents holds the value of the "max_amount_cents" field.
	MaxAmountCents *int64 `json:"max_amount_cents,omitempty"`
	// SuggestedAmountsCents holds the value of the "suggested_amounts_cents" field.
	SuggestedAmountsCents []int64 `json:"suggested_amounts_cents,omitempty"`
	// ExchangeRate holds the value of the "exchange_rate" field.
	ExchangeRate *float64 `json:"exchange_rate,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentProductQuery when eager-loading is set.
	Edges        PaymentProductEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PaymentProductEdges holds the relations/edges for other nodes in the graph.
type PaymentProductEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Orders holds the value of the orders edge.
	Orders []*PaymentOrder `json:"orders,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentProductEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// OrdersOrErr returns the Orders value or an error if the edge
// was not loaded in eager-loading.
func (e PaymentProductEdges) OrdersOrErr() ([]*PaymentOrder, error) {
	if e.loadedTypes[1] {
		return e.Orders, nil
	}
	return nil, &NotLoadedError{edge: "orders"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentProduct) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentproduct.FieldSuggestedAmountsCents:
			values[i] = new([]byte)
		case paymentproduct.FieldAllowCustomAmount:
			values[i] = new(sql.NullBool)
		case paymentproduct.FieldCreditBalance, paymentproduct.FieldExchangeRate:
			values[i] = new(sql.NullFloat64)
		case paymentproduct.FieldID, paymentproduct.FieldSortOrder, paymentproduct.FieldPriceCents, paymentproduct.FieldGroupID, paymentproduct.FieldValidityDays, paymentproduct.FieldMinAmountCents, paymentproduct.FieldMaxAmountCents:
			values[i] = new(sql.NullInt64)
		case paymentproduct.FieldKind, paymentproduct.FieldName, paymentproduct.FieldDescriptionMd, paymentproduct.FieldStatus, paymentproduct.FieldCurrency:
			values[i] = new(sql.NullString)
		case paymentproduct.FieldCreatedAt, paymentproduct.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentProduct fields.
func (_m *PaymentProduct) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentproduct.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentproduct.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentproduct.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case paymentproduct.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case paymentproduct.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case paymentproduct.FieldDescriptionMd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description_md", values[i])
			} else if value.Valid {
				_m.DescriptionMd = value.String
			}
		case paymentproduct.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case paymentproduct.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case paymentproduct.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case paymentproduct.FieldPriceCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_cents", values[i])
			} else if value.Valid {
				_m.PriceCents = value.Int64
			}
		case paymentproduct.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case paymentproduct.FieldValidityDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field validity_days", values[i])
			} else if value.Valid {
				_m.ValidityDays = new(int)
				*_m.ValidityDays = int(value.Int64)
			}
		case paymentproduct.FieldCreditBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_balance", values[i])
			} else if value.Valid {
				_m.CreditBalance = new(float64)
				*_m.CreditBalance = value.Float64
			}
		case paymentproduct.FieldAllowCustomAmount:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_custom_amount", values[i])
			} else if value.Valid {
				_m.AllowCustomAmount = value.Bool
			}
		case paymentproduct.FieldMinAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field min_amount_cents", values[i])
			} else if value.Valid {
				_m.MinAmountCents = new(int64)
				*_m.MinAmountCents = value.Int64
			}
		case paymentproduct.FieldMaxAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_amount_cents", values[i])
			} else if value.Valid {
				_m.MaxAmountCents = new(int64)
				*_m.MaxAmountCents = value.Int64
			}
		case paymentproduct.FieldSuggestedAmountsCents:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field suggested_amounts_cents", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SuggestedAmountsCents); err != nil {
					return fmt.Errorf("unmarshal field suggested_amounts_cents: %w", err)
				}
			}
		case paymentproduct.FieldExchangeRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field exchange_rate", values[i])
			} else if value.Valid {
				_m.ExchangeRate = new(float64)
				*_m.ExchangeRate = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentProduct.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentProduct) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the PaymentProduct entity.
func (_m *PaymentProduct) QueryGroup() *GroupQuery {
	return NewPaymentProductClient(_m.config).QueryGroup(_m)
}

// QueryOrders queries the "orders" edge of the PaymentProduct entity.
func (_m *PaymentProduct) QueryOrders() *PaymentOrderQuery {
	return NewPaymentProductClient(_m.config).QueryOrders(_m)
}

// Update returns a builder for updating this PaymentProduct.
// Note that you need to call PaymentProduct.Unwrap() before calling this method if this PaymentProduct
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentProduct) Update() *PaymentProductUpdateOne {
	return NewPaymentProductClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentProduct entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentProduct) Unwrap() *PaymentProduct {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentProduct is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentProduct) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentProduct(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description_md=")
	builder.WriteString(_m.DescriptionMd)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("price_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceCents))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ValidityDays; v != nil {
		builder.WriteString("validity_days=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreditBalance; v != nil {
		builder.WriteString("credit_balance=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("allow_custom_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowCustomAmount))
	builder.WriteString(", ")
	if v := _m.MinAmountCents; v != nil {
		builder.WriteString("min_amount_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MaxAmountCents; v != nil {
		builder.WriteString("max_amount_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("suggested_amounts_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuggestedAmountsCents))
	builder.WriteString(", ")
	if v := _m.ExchangeRate; v != nil {
		builder.WriteString("exchange_rate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PaymentProducts is a parsable slice of PaymentProduct.
type PaymentProducts []*PaymentProduct
