// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentnotification"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentNotificationDelete is the builder for deleting a PaymentNotification entity.
type PaymentNotificationDelete struct {
	config
	hooks    []Hook
	mutation *PaymentNotificationMutation
}

// Where appends a list predicates to the PaymentNotificationDelete builder.
func (_d *PaymentNotificationDelete) Where(ps ...predicate.PaymentNotification) *PaymentNotificationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PaymentNotificationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentNotificationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PaymentNotificationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymentnotification.Table, sqlgraph.NewFieldSpec(paymentnotification.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PaymentNotificationDeleteOne is the builder for deleting a single PaymentNotification entity.
type PaymentNotificationDeleteOne struct {
	_d *PaymentNotificationDelete
}

// Where appends a list predicates to the PaymentNotificationDelete builder.
func (_d *PaymentNotificationDeleteOne) Where(ps ...predicate.PaymentNotification) *PaymentNotificationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PaymentNotificationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentnotification.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentNotificationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
