// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentnotification"
)

// PaymentNotification is the model entity for the PaymentNotification schema.
type PaymentNotification struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// EventID holds the value of the "event_id" field.
	EventID string `json:"event_id,omitempty"`
	// OrderNo holds the value of the "order_no" field.
	OrderNo *string `json:"order_no,omitempty"`
	// ProviderTradeNo holds the value of the "provider_trade_no" field.
	ProviderTradeNo *string `json:"provider_trade_no,omitempty"`
	// AmountCents holds the value of the "amount_cents" field.
	AmountCents *int64 `json:"amount_cents,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency *string `json:"currency,omitempty"`
	// Verified holds the value of the "verified" field.
	Verified bool `json:"verified,omitempty"`
	// Processed holds the value of the "processed" field.
	Processed bool `json:"processed,omitempty"`
	// ProcessError holds the value of the "process_error" field.
	ProcessError *string `json:"process_error,omitempty"`
	// RawBody holds the value of the "raw_body" field.
	RawBody string `json:"raw_body,omitempty"`
	// ReceivedAt holds the value of the "received_at" field.
	ReceivedAt   time.Time `json:"received_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentNotification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentnotification.FieldVerified, paymentnotification.FieldProcessed:
			values[i] = new(sql.NullBool)
		case paymentnotification.FieldID, paymentnotification.FieldAmountCents:
			values[i] = new(sql.NullInt64)
		case paymentnotification.FieldProvider, paymentnotification.FieldEventID, paymentnotification.FieldOrderNo, paymentnotification.FieldProviderTradeNo, paymentnotification.FieldCurrency, paymentnotification.FieldProcessError, paymentnotification.FieldRawBody:
			values[i] = new(sql.NullString)
		case paymentnotification.FieldReceivedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentNotification fields.
func (_m *PaymentNotification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentnotification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentnotification.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case paymentnotification.FieldEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value.Valid {
				_m.EventID = value.String
			}
		case paymentnotification.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = new(string)
				*_m.OrderNo = value.String
			}
		case paymentnotification.FieldProviderTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_trade_no", values[i])
			} else if value.Valid {
				_m.ProviderTradeNo = new(string)
				*_m.ProviderTradeNo = value.String
			}
		case paymentnotification.FieldAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cents", values[i])
			} else if value.Valid {
				_m.AmountCents = new(int64)
				*_m.AmountCents = value.Int64
			}
		case paymentnotification.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = new(string)
				*_m.Currency = value.String
			}
		case paymentnotification.FieldVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field verified", values[i])
			} else if value.Valid {
				_m.Verified = value.Bool
			}
		case paymentnotification.FieldProcessed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field processed", values[i])
			} else if value.Valid {
				_m.Processed = value.Bool
			}
		case paymentnotification.FieldProcessError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field process_error", values[i])
			} else if value.Valid {
				_m.ProcessError = new(string)
				*_m.ProcessError = value.String
			}
		case paymentnotification.FieldRawBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_body", values[i])
			} else if value.Valid {
				_m.RawBody = value.String
			}
		case paymentnotification.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				_m.ReceivedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentNotification.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentNotification) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentNotification.
// Note that you need to call PaymentNotification.Unwrap() before calling this method if this PaymentNotification
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentNotification) Update() *PaymentNotificationUpdateOne {
	return NewPaymentNotificationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentNotification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentNotification) Unwrap() *PaymentNotification {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentNotification is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentNotification) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentNotification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("event_id=")
	builder.WriteString(_m.EventID)
	builder.WriteString(", ")
	if v := _m.OrderNo; v != nil {
		builder.WriteString("order_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProviderTradeNo; v != nil {
		builder.WriteString("provider_trade_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AmountCents; v != nil {
		builder.WriteString("amount_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Currency; v != nil {
		builder.WriteString("currency=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("verified=")
	builder.WriteString(fmt.Sprintf("%v", _m.Verified))
	builder.WriteString(", ")
	builder.WriteString("processed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Processed))
	builder.WriteString(", ")
	if v := _m.ProcessError; v != nil {
		builder.WriteString("process_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("raw_body=")
	builder.WriteString(_m.RawBody)
	builder.WriteString(", ")
	builder.WriteString("received_at=")
	builder.WriteString(_m.ReceivedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentNotifications is a parsable slice of PaymentNotification.
type PaymentNotifications []*PaymentNotification
