// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/entitlementevent"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/paymentproduct"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentOrderCreate is the builder for creating a PaymentOrder entity.
type PaymentOrderCreate struct {
	config
	mutation *PaymentOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentOrderCreate) SetCreatedAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCreatedAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentOrderCreate) SetUpdatedAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableUpdatedAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *PaymentOrderCreate) SetOrderNo(v string) *PaymentOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PaymentOrderCreate) SetUserID(v int64) *PaymentOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *PaymentOrderCreate) SetKind(v string) *PaymentOrderCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *PaymentOrderCreate) SetProductID(v int64) *PaymentOrderCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableProductID(v *int64) *PaymentOrderCreate {
	if v != nil {
		_c.SetProductID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentOrderCreate) SetStatus(v string) *PaymentOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableStatus(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *PaymentOrderCreate) SetProvider(v string) *PaymentOrderCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableProvider(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PaymentOrderCreate) SetCurrency(v string) *PaymentOrderCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCurrency(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetAmountCents sets the "amount_cents" field.
func (_c *PaymentOrderCreate) SetAmountCents(v int64) *PaymentOrderCreate {
	_c.mutation.SetAmountCents(v)
	return _c
}

// SetClientRequestID sets the "client_request_id" field.
func (_c *PaymentOrderCreate) SetClientRequestID(v string) *PaymentOrderCreate {
	_c.mutation.SetClientRequestID(v)
	return _c
}

// SetNillableClientRequestID sets the "client_request_id" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableClientRequestID(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetClientRequestID(*v)
	}
	return _c
}

// SetProviderTradeNo sets the "provider_trade_no" field.
func (_c *PaymentOrderCreate) SetProviderTradeNo(v string) *PaymentOrderCreate {
	_c.mutation.SetProviderTradeNo(v)
	return _c
}

// SetNillableProviderTradeNo sets the "provider_trade_no" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableProviderTradeNo(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetProviderTradeNo(*v)
	}
	return _c
}

// SetPayURL sets the "pay_url" field.
func (_c *PaymentOrderCreate) SetPayURL(v string) *PaymentOrderCreate {
	_c.mutation.SetPayURL(v)
	return _c
}

// SetNillablePayURL sets the "pay_url" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillablePayURL(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetPayURL(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *PaymentOrderCreate) SetExpiresAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableExpiresAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *PaymentOrderCreate) SetPaidAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillablePaidAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (_c *PaymentOrderCreate) SetFulfilledAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetFulfilledAt(v)
	return _c
}

// SetNillableFulfilledAt sets the "fulfilled_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableFulfilledAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetFulfilledAt(*v)
	}
	return _c
}

// SetGrantGroupID sets the "grant_group_id" field.
func (_c *PaymentOrderCreate) SetGrantGroupID(v int64) *PaymentOrderCreate {
	_c.mutation.SetGrantGroupID(v)
	return _c
}

// SetNillableGrantGroupID sets the "grant_group_id" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableGrantGroupID(v *int64) *PaymentOrderCreate {
	if v != nil {
		_c.SetGrantGroupID(*v)
	}
	return _c
}

// SetGrantValidityDays sets the "grant_validity_days" field.
func (_c *PaymentOrderCreate) SetGrantValidityDays(v int) *PaymentOrderCreate {
	_c.mutation.SetGrantValidityDays(v)
	return _c
}

// SetNillableGrantValidityDays sets the "grant_validity_days" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableGrantValidityDays(v *int) *PaymentOrderCreate {
	if v != nil {
		_c.SetGrantValidityDays(*v)
	}
	return _c
}

// SetGrantCreditBalance sets the "grant_credit_balance" field.
func (_c *PaymentOrderCreate) SetGrantCreditBalance(v float64) *PaymentOrderCreate {
	_c.mutation.SetGrantCreditBalance(v)
	return _c
}

// SetNillableGrantCreditBalance sets the "grant_credit_balance" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableGrantCreditBalance(v *float64) *PaymentOrderCreate {
	if v != nil {
		_c.SetGrantCreditBalance(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *PaymentOrderCreate) SetNotes(v string) *PaymentOrderCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableNotes(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PaymentOrderCreate) SetUser(v *User) *PaymentOrderCreate {
	return _c.SetUserID(v.ID)
}

// SetProduct sets the "product" edge to the PaymentProduct entity.
func (_c *PaymentOrderCreate) SetProduct(v *PaymentProduct) *PaymentOrderCreate {
	return _c.SetProductID(v.ID)
}

// SetGrantGroup sets the "grant_group" edge to the Group entity.
func (_c *PaymentOrderCreate) SetGrantGroup(v *Group) *PaymentOrderCreate {
	return _c.SetGrantGroupID(v.ID)
}

// AddEntitlementEventIDs adds the "entitlement_events" edge to the EntitlementEvent entity by IDs.
func (_c *PaymentOrderCreate) AddEntitlementEventIDs(ids ...int64) *PaymentOrderCreate {
	_c.mutation.AddEntitlementEventIDs(ids...)
	return _c
}

// AddEntitlementEvents adds the "entitlement_events" edges to the EntitlementEvent entity.
func (_c *PaymentOrderCreate) AddEntitlementEvents(v ...*EntitlementEvent) *PaymentOrderCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEntitlementEventIDs(ids...)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_c *PaymentOrderCreate) Mutation() *PaymentOrderMutation {
	return _c.mutation
}

// Save creates the PaymentOrder in the database.
func (_c *PaymentOrderCreate) Save(ctx context.Context) (*PaymentOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentOrderCreate) SaveX(ctx context.Context) *PaymentOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentOrderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := paymentorder.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := paymentorder.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentOrderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentOrder.updated_at"`)}
	}
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "PaymentOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := paymentorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PaymentOrder.user_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "PaymentOrder.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := paymentorder.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "PaymentOrder.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := paymentorder.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "PaymentOrder.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := paymentorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountCents(); !ok {
		return &ValidationError{Name: "amount_cents", err: errors.New(`ent: missing required field "PaymentOrder.amount_cents"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PaymentOrder.user"`)}
	}
	return nil
}

func (_c *PaymentOrderCreate) sqlSave(ctx context.Context) (*PaymentOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentOrderCreate) createSpec() (*PaymentOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentorder.Table, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(paymentorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(paymentorder.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(paymentorder.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(paymentorder.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.AmountCents(); ok {
		_spec.SetField(paymentorder.FieldAmountCents, field.TypeInt64, value)
		_node.AmountCents = value
	}
	if value, ok := _c.mutation.ClientRequestID(); ok {
		_spec.SetField(paymentorder.FieldClientRequestID, field.TypeString, value)
		_node.ClientRequestID = &value
	}
	if value, ok := _c.mutation.ProviderTradeNo(); ok {
		_spec.SetField(paymentorder.FieldProviderTradeNo, field.TypeString, value)
		_node.ProviderTradeNo = &value
	}
	if value, ok := _c.mutation.PayURL(); ok {
		_spec.SetField(paymentorder.FieldPayURL, field.TypeString, value)
		_node.PayURL = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(paymentorder.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.FulfilledAt(); ok {
		_spec.SetField(paymentorder.FieldFulfilledAt, field.TypeTime, value)
		_node.FulfilledAt = &value
	}
	if value, ok := _c.mutation.GrantValidityDays(); ok {
		_spec.SetField(paymentorder.FieldGrantValidityDays, field.TypeInt, value)
		_node.GrantValidityDays = &value
	}
	if value, ok := _c.mutation.GrantCreditBalance(); ok {
		_spec.SetField(paymentorder.FieldGrantCreditBalance, field.TypeFloat64, value)
		_node.GrantCreditBalance = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(paymentorder.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.ProductTable,
			Columns: []string{paymentorder.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GrantGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.GrantGroupTable,
			Columns: []string{paymentorder.GrantGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GrantGroupID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EntitlementEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentorder.EntitlementEventsTable,
			Columns: []string{paymentorder.EntitlementEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entitlementevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentOrderCreate) OnConflict(opts ...sql.ConflictOption) *PaymentOrderUpsertOne {
	_c.conflict = opts
	return &PaymentOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentOrderCreate) OnConflictColumns(columns ...string) *PaymentOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderUpsertOne{
		create: _c,
	}
}

type (
	// PaymentOrderUpsertOne is the builder for "upsert"-ing
	//  one PaymentOrder node.
	PaymentOrderUpsertOne struct {
		create *PaymentOrderCreate
	}

	// PaymentOrderUpsert is the "OnConflict" setter.
	PaymentOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsert) SetUpdatedAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateUpdatedAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldUpdatedAt)
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *PaymentOrderUpsert) SetOrderNo(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateOrderNo() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldOrderNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsert) SetUserID(v int64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateUserID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldUserID)
	return u
}

// SetKind sets the "kind" field.
func (u *PaymentOrderUpsert) SetKind(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateKind() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldKind)
	return u
}

// SetProductID sets the "product_id" field.
func (u *PaymentOrderUpsert) SetProductID(v int64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateProductID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldProductID)
	return u
}

// ClearProductID clears the value of the "product_id" field.
func (u *PaymentOrderUpsert) ClearProductID() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldProductID)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsert) SetStatus(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateStatus() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldStatus)
	return u
}

// SetProvider sets the "provider" field.
func (u *PaymentOrderUpsert) SetProvider(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateProvider() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldProvider)
	return u
}

// SetCurrency sets the "currency" field.
func (u *PaymentOrderUpsert) SetCurrency(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateCurrency() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldCurrency)
	return u
}

// SetAmountCents sets the "amount_cents" field.
func (u *PaymentOrderUpsert) SetAmountCents(v int64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldAmountCents, v)
	return u
}

// UpdateAmountCents sets the "amount_cents" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateAmountCents() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldAmountCents)
	return u
}

// AddAmountCents adds v to the "amount_cents" field.
func (u *PaymentOrderUpsert) AddAmountCents(v int64) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldAmountCents, v)
	return u
}

// SetClientRequestID sets the "client_request_id" field.
func (u *PaymentOrderUpsert) SetClientRequestID(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldClientRequestID, v)
	return u
}

// UpdateClientRequestID sets the "client_request_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateClientRequestID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldClientRequestID)
	return u
}

// ClearClientRequestID clears the value of the "client_request_id" field.
func (u *PaymentOrderUpsert) ClearClientRequestID() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldClientRequestID)
	return u
}

// SetProviderTradeNo sets the "provider_trade_no" field.
func (u *PaymentOrderUpsert) SetProviderTradeNo(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldProviderTradeNo, v)
	return u
}

// UpdateProviderTradeNo sets the "provider_trade_no" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateProviderTradeNo() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldProviderTradeNo)
	return u
}

// ClearProviderTradeNo clears the value of the "provider_trade_no" field.
func (u *PaymentOrderUpsert) ClearProviderTradeNo() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldProviderTradeNo)
	return u
}

// SetPayURL sets the "pay_url" field.
func (u *PaymentOrderUpsert) SetPayURL(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldPayURL, v)
	return u
}

// UpdatePayURL sets the "pay_url" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdatePayURL() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldPayURL)
	return u
}

// ClearPayURL clears the value of the "pay_url" field.
func (u *PaymentOrderUpsert) ClearPayURL() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldPayURL)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *PaymentOrderUpsert) SetExpiresAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateExpiresAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *PaymentOrderUpsert) ClearExpiresAt() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldExpiresAt)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsert) SetPaidAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdatePaidAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsert) ClearPaidAt() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldPaidAt)
	return u
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (u *PaymentOrderUpsert) SetFulfilledAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldFulfilledAt, v)
	return u
}

// UpdateFulfilledAt sets the "fulfilled_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateFulfilledAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldFulfilledAt)
	return u
}

// ClearFulfilledAt clears the value of the "fulfilled_at" field.
func (u *PaymentOrderUpsert) ClearFulfilledAt() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldFulfilledAt)
	return u
}

// SetGrantGroupID sets the "grant_group_id" field.
func (u *PaymentOrderUpsert) SetGrantGroupID(v int64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldGrantGroupID, v)
	return u
}

// UpdateGrantGroupID sets the "grant_group_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateGrantGroupID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldGrantGroupID)
	return u
}

// ClearGrantGroupID clears the value of the "grant_group_id" field.
func (u *PaymentOrderUpsert) ClearGrantGroupID() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldGrantGroupID)
	return u
}

// SetGrantValidityDays sets the "grant_validity_days" field.
func (u *PaymentOrderUpsert) SetGrantValidityDays(v int) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldGrantValidityDays, v)
	return u
}

// UpdateGrantValidityDays sets the "grant_validity_days" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateGrantValidityDays() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldGrantValidityDays)
	return u
}

// AddGrantValidityDays adds v to the "grant_validity_days" field.
func (u *PaymentOrderUpsert) AddGrantValidityDays(v int) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldGrantValidityDays, v)
	return u
}

// ClearGrantValidityDays clears the value of the "grant_validity_days" field.
func (u *PaymentOrderUpsert) ClearGrantValidityDays() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldGrantValidityDays)
	return u
}

// SetGrantCreditBalance sets the "grant_credit_balance" field.
func (u *PaymentOrderUpsert) SetGrantCreditBalance(v float64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldGrantCreditBalance, v)
	return u
}

// UpdateGrantCreditBalance sets the "grant_credit_balance" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateGrantCreditBalance() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldGrantCreditBalance)
	return u
}

// AddGrantCreditBalance adds v to the "grant_credit_balance" field.
func (u *PaymentOrderUpsert) AddGrantCreditBalance(v float64) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldGrantCreditBalance, v)
	return u
}

// ClearGrantCreditBalance clears the value of the "grant_credit_balance" field.
func (u *PaymentOrderUpsert) ClearGrantCreditBalance() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldGrantCreditBalance)
	return u
}

// SetNotes sets the "notes" field.
func (u *PaymentOrderUpsert) SetNotes(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateNotes() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *PaymentOrderUpsert) ClearNotes() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentOrderUpsertOne) UpdateNewValues() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentOrderUpsertOne) Ignore() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderUpsertOne) DoNothing() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderCreate.OnConflict
// documentation for more info.
func (u *PaymentOrderUpsertOne) Update(set func(*PaymentOrderUpsert)) *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsertOne) SetUpdatedAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateUpdatedAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *PaymentOrderUpsertOne) SetOrderNo(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateOrderNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsertOne) SetUserID(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateUserID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetKind sets the "kind" field.
func (u *PaymentOrderUpsertOne) SetKind(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateKind() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateKind()
	})
}

// SetProductID sets the "product_id" field.
func (u *PaymentOrderUpsertOne) SetProductID(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateProductID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProductID()
	})
}

// ClearProductID clears the value of the "product_id" field.
func (u *PaymentOrderUpsertOne) ClearProductID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProductID()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsertOne) SetStatus(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateStatus() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetProvider sets the "provider" field.
func (u *PaymentOrderUpsertOne) SetProvider(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateProvider() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProvider()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentOrderUpsertOne) SetCurrency(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateCurrency() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetAmountCents sets the "amount_cents" field.
func (u *PaymentOrderUpsertOne) SetAmountCents(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAmountCents(v)
	})
}

// AddAmountCents adds v to the "amount_cents" field.
func (u *PaymentOrderUpsertOne) AddAmountCents(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddAmountCents(v)
	})
}

// UpdateAmountCents sets the "amount_cents" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateAmountCents() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAmountCents()
	})
}

// SetClientRequestID sets the "client_request_id" field.
func (u *PaymentOrderUpsertOne) SetClientRequestID(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetClientRequestID(v)
	})
}

// UpdateClientRequestID sets the "client_request_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateClientRequestID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateClientRequestID()
	})
}

// ClearClientRequestID clears the value of the "client_request_id" field.
func (u *PaymentOrderUpsertOne) ClearClientRequestID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearClientRequestID()
	})
}

// SetProviderTradeNo sets the "provider_trade_no" field.
func (u *PaymentOrderUpsertOne) SetProviderTradeNo(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProviderTradeNo(v)
	})
}

// UpdateProviderTradeNo sets the "provider_trade_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateProviderTradeNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProviderTradeNo()
	})
}

// ClearProviderTradeNo clears the value of the "provider_trade_no" field.
func (u *PaymentOrderUpsertOne) ClearProviderTradeNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProviderTradeNo()
	})
}

// SetPayURL sets the "pay_url" field.
func (u *PaymentOrderUpsertOne) SetPayURL(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPayURL(v)
	})
}

// UpdatePayURL sets the "pay_url" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdatePayURL() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePayURL()
	})
}

// ClearPayURL clears the value of the "pay_url" field.
func (u *PaymentOrderUpsertOne) ClearPayURL() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPayURL()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *PaymentOrderUpsertOne) SetExpiresAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateExpiresAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *PaymentOrderUpsertOne) ClearExpiresAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearExpiresAt()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsertOne) SetPaidAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdatePaidAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsertOne) ClearPaidAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (u *PaymentOrderUpsertOne) SetFulfilledAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetFulfilledAt(v)
	})
}

// UpdateFulfilledAt sets the "fulfilled_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateFulfilledAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateFulfilledAt()
	})
}

// ClearFulfilledAt clears the value of the "fulfilled_at" field.
func (u *PaymentOrderUpsertOne) ClearFulfilledAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearFulfilledAt()
	})
}

// SetGrantGroupID sets the "grant_group_id" field.
func (u *PaymentOrderUpsertOne) SetGrantGroupID(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetGrantGroupID(v)
	})
}

// UpdateGrantGroupID sets the "grant_group_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateGrantGroupID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateGrantGroupID()
	})
}

// ClearGrantGroupID clears the value of the "grant_group_id" field.
func (u *PaymentOrderUpsertOne) ClearGrantGroupID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearGrantGroupID()
	})
}

// SetGrantValidityDays sets the "grant_validity_days" field.
func (u *PaymentOrderUpsertOne) SetGrantValidityDays(v int) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetGrantValidityDays(v)
	})
}

// AddGrantValidityDays adds v to the "grant_validity_days" field.
func (u *PaymentOrderUpsertOne) AddGrantValidityDays(v int) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddGrantValidityDays(v)
	})
}

// UpdateGrantValidityDays sets the "grant_validity_days" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateGrantValidityDays() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateGrantValidityDays()
	})
}

// ClearGrantValidityDays clears the value of the "grant_validity_days" field.
func (u *PaymentOrderUpsertOne) ClearGrantValidityDays() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearGrantValidityDays()
	})
}

// SetGrantCreditBalance sets the "grant_credit_balance" field.
func (u *PaymentOrderUpsertOne) SetGrantCreditBalance(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetGrantCreditBalance(v)
	})
}

// AddGrantCreditBalance adds v to the "grant_credit_balance" field.
func (u *PaymentOrderUpsertOne) AddGrantCreditBalance(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddGrantCreditBalance(v)
	})
}

// UpdateGrantCreditBalance sets the "grant_credit_balance" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateGrantCreditBalance() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateGrantCreditBalance()
	})
}

// ClearGrantCreditBalance clears the value of the "grant_credit_balance" field.
func (u *PaymentOrderUpsertOne) ClearGrantCreditBalance() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearGrantCreditBalance()
	})
}

// SetNotes sets the "notes" field.
func (u *PaymentOrderUpsertOne) SetNotes(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateNotes() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *PaymentOrderUpsertOne) ClearNotes() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *PaymentOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentOrderCreateBulk is the builder for creating many PaymentOrder entities in bulk.
type PaymentOrderCreateBulk struct {
	config
	err      error
	builders []*PaymentOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentOrder entities in the database.
func (_c *PaymentOrderCreateBulk) Save(ctx context.Context) ([]*PaymentOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentOrderCreateBulk) SaveX(ctx context.Context) []*PaymentOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentOrderUpsertBulk {
	_c.conflict = opts
	return &PaymentOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentOrderCreateBulk) OnConflictColumns(columns ...string) *PaymentOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderUpsertBulk{
		create: _c,
	}
}

// PaymentOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentOrder nodes.
type PaymentOrderUpsertBulk struct {
	create *PaymentOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentOrderUpsertBulk) UpdateNewValues() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentOrderUpsertBulk) Ignore() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderUpsertBulk) DoNothing() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentOrderUpsertBulk) Update(set func(*PaymentOrderUpsert)) *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsertBulk) SetUpdatedAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateUpdatedAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *PaymentOrderUpsertBulk) SetOrderNo(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateOrderNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsertBulk) SetUserID(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateUserID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetKind sets the "kind" field.
func (u *PaymentOrderUpsertBulk) SetKind(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateKind() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateKind()
	})
}

// SetProductID sets the "product_id" field.
func (u *PaymentOrderUpsertBulk) SetProductID(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateProductID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProductID()
	})
}

// ClearProductID clears the value of the "product_id" field.
func (u *PaymentOrderUpsertBulk) ClearProductID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProductID()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsertBulk) SetStatus(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateStatus() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetProvider sets the "provider" field.
func (u *PaymentOrderUpsertBulk) SetProvider(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateProvider() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProvider()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentOrderUpsertBulk) SetCurrency(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateCurrency() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetAmountCents sets the "amount_cents" field.
func (u *PaymentOrderUpsertBulk) SetAmountCents(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAmountCents(v)
	})
}

// AddAmountCents adds v to the "amount_cents" field.
func (u *PaymentOrderUpsertBulk) AddAmountCents(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddAmountCents(v)
	})
}

// UpdateAmountCents sets the "amount_cents" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateAmountCents() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAmountCents()
	})
}

// SetClientRequestID sets the "client_request_id" field.
func (u *PaymentOrderUpsertBulk) SetClientRequestID(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetClientRequestID(v)
	})
}

// UpdateClientRequestID sets the "client_request_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateClientRequestID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateClientRequestID()
	})
}

// ClearClientRequestID clears the value of the "client_request_id" field.
func (u *PaymentOrderUpsertBulk) ClearClientRequestID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearClientRequestID()
	})
}

// SetProviderTradeNo sets the "provider_trade_no" field.
func (u *PaymentOrderUpsertBulk) SetProviderTradeNo(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProviderTradeNo(v)
	})
}

// UpdateProviderTradeNo sets the "provider_trade_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateProviderTradeNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProviderTradeNo()
	})
}

// ClearProviderTradeNo clears the value of the "provider_trade_no" field.
func (u *PaymentOrderUpsertBulk) ClearProviderTradeNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProviderTradeNo()
	})
}

// SetPayURL sets the "pay_url" field.
func (u *PaymentOrderUpsertBulk) SetPayURL(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPayURL(v)
	})
}

// UpdatePayURL sets the "pay_url" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdatePayURL() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePayURL()
	})
}

// ClearPayURL clears the value of the "pay_url" field.
func (u *PaymentOrderUpsertBulk) ClearPayURL() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPayURL()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *PaymentOrderUpsertBulk) SetExpiresAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateExpiresAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *PaymentOrderUpsertBulk) ClearExpiresAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearExpiresAt()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsertBulk) SetPaidAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdatePaidAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsertBulk) ClearPaidAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (u *PaymentOrderUpsertBulk) SetFulfilledAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetFulfilledAt(v)
	})
}

// UpdateFulfilledAt sets the "fulfilled_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateFulfilledAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateFulfilledAt()
	})
}

// ClearFulfilledAt clears the value of the "fulfilled_at" field.
func (u *PaymentOrderUpsertBulk) ClearFulfilledAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearFulfilledAt()
	})
}

// SetGrantGroupID sets the "grant_group_id" field.
func (u *PaymentOrderUpsertBulk) SetGrantGroupID(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetGrantGroupID(v)
	})
}

// UpdateGrantGroupID sets the "grant_group_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateGrantGroupID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateGrantGroupID()
	})
}

// ClearGrantGroupID clears the value of the "grant_group_id" field.
func (u *PaymentOrderUpsertBulk) ClearGrantGroupID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearGrantGroupID()
	})
}

// SetGrantValidityDays sets the "grant_validity_days" field.
func (u *PaymentOrderUpsertBulk) SetGrantValidityDays(v int) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetGrantValidityDays(v)
	})
}

// AddGrantValidityDays adds v to the "grant_validity_days" field.
func (u *PaymentOrderUpsertBulk) AddGrantValidityDays(v int) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddGrantValidityDays(v)
	})
}

// UpdateGrantValidityDays sets the "grant_validity_days" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateGrantValidityDays() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateGrantValidityDays()
	})
}

// ClearGrantValidityDays clears the value of the "grant_validity_days" field.
func (u *PaymentOrderUpsertBulk) ClearGrantValidityDays() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearGrantValidityDays()
	})
}

// SetGrantCreditBalance sets the "grant_credit_balance" field.
func (u *PaymentOrderUpsertBulk) SetGrantCreditBalance(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetGrantCreditBalance(v)
	})
}

// AddGrantCreditBalance adds v to the "grant_credit_balance" field.
func (u *PaymentOrderUpsertBulk) AddGrantCreditBalance(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddGrantCreditBalance(v)
	})
}

// UpdateGrantCreditBalance sets the "grant_credit_balance" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateGrantCreditBalance() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateGrantCreditBalance()
	})
}

// ClearGrantCreditBalance clears the value of the "grant_credit_balance" field.
func (u *PaymentOrderUpsertBulk) ClearGrantCreditBalance() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearGrantCreditBalance()
	})
}

// SetNotes sets the "notes" field.
func (u *PaymentOrderUpsertBulk) SetNotes(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateNotes() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *PaymentOrderUpsertBulk) ClearNotes() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *PaymentOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
