// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/paymentproduct"
)

// PaymentProductCreate is the builder for creating a PaymentProduct entity.
type PaymentProductCreate struct {
	config
	mutation *PaymentProductMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentProductCreate) SetCreatedAt(v time.Time) *PaymentProductCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillableCreatedAt(v *time.Time) *PaymentProductCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentProductCreate) SetUpdatedAt(v time.Time) *PaymentProductCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillableUpdatedAt(v *time.Time) *PaymentProductCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *PaymentProductCreate) SetKind(v string) *PaymentProductCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PaymentProductCreate) SetName(v string) *PaymentProductCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescriptionMd sets the "description_md" field.
func (_c *PaymentProductCreate) SetDescriptionMd(v string) *PaymentProductCreate {
	_c.mutation.SetDescriptionMd(v)
	return _c
}

// SetNillableDescriptionMd sets the "description_md" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillableDescriptionMd(v *string) *PaymentProductCreate {
	if v != nil {
		_c.SetDescriptionMd(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentProductCreate) SetStatus(v string) *PaymentProductCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillableStatus(v *string) *PaymentProductCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *PaymentProductCreate) SetSortOrder(v int) *PaymentProductCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillableSortOrder(v *int) *PaymentProductCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PaymentProductCreate) SetCurrency(v string) *PaymentProductCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillableCurrency(v *string) *PaymentProductCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetPriceCents sets the "price_cents" field.
func (_c *PaymentProductCreate) SetPriceCents(v int64) *PaymentProductCreate {
	_c.mutation.SetPriceCents(v)
	return _c
}

// SetNillablePriceCents sets the "price_cents" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillablePriceCents(v *int64) *PaymentProductCreate {
	if v != nil {
		_c.SetPriceCents(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *PaymentProductCreate) SetGroupID(v int64) *PaymentProductCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillableGroupID(v *int64) *PaymentProductCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *PaymentProductCreate) SetValidityDays(v int) *PaymentProductCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillableValidityDays(v *int) *PaymentProductCreate {
	if v != nil {
		_c.SetValidityDays(*v)
	}
	return _c
}

// SetCreditBalance sets the "credit_balance" field.
func (_c *PaymentProductCreate) SetCreditBalance(v float64) *PaymentProductCreate {
	_c.mutation.SetCreditBalance(v)
	return _c
}

// SetNillableCreditBalance sets the "credit_balance" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillableCreditBalance(v *float64) *PaymentProductCreate {
	if v != nil {
		_c.SetCreditBalance(*v)
	}
	return _c
}

// SetAllowCustomAmount sets the "allow_custom_amount" field.
func (_c *PaymentProductCreate) SetAllowCustomAmount(v bool) *PaymentProductCreate {
	_c.mutation.SetAllowCustomAmount(v)
	return _c
}

// SetNillableAllowCustomAmount sets the "allow_custom_amount" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillableAllowCustomAmount(v *bool) *PaymentProductCreate {
	if v != nil {
		_c.SetAllowCustomAmount(*v)
	}
	return _c
}

// SetMinAmountCents sets the "min_amount_cents" field.
func (_c *PaymentProductCreate) SetMinAmountCents(v int64) *PaymentProductCreate {
	_c.mutation.SetMinAmountCents(v)
	return _c
}

// SetNillableMinAmountCents sets the "min_amount_cents" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillableMinAmountCents(v *int64) *PaymentProductCreate {
	if v != nil {
		_c.SetMinAmountCents(*v)
	}
	return _c
}

// SetMaxAmountCents sets the "max_amount_cents" field.
func (_c *PaymentProductCreate) SetMaxAmountCents(v int64) *PaymentProductCreate {
	_c.mutation.SetMaxAmountCents(v)
	return _c
}

// SetNillableMaxAmountCents sets the "max_amount_cents" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillableMaxAmountCents(v *int64) *PaymentProductCreate {
	if v != nil {
		_c.SetMaxAmountCents(*v)
	}
	return _c
}

// SetSuggestedAmountsCents sets the "suggested_amounts_cents" field.
func (_c *PaymentProductCreate) SetSuggestedAmountsCents(v []int64) *PaymentProductCreate {
	_c.mutation.SetSuggestedAmountsCents(v)
	return _c
}

// SetExchangeRate sets the "exchange_rate" field.
func (_c *PaymentProductCreate) SetExchangeRate(v float64) *PaymentProductCreate {
	_c.mutation.SetExchangeRate(v)
	return _c
}

// SetNillableExchangeRate sets the "exchange_rate" field if the given value is not nil.
func (_c *PaymentProductCreate) SetNillableExchangeRate(v *float64) *PaymentProductCreate {
	if v != nil {
		_c.SetExchangeRate(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *PaymentProductCreate) SetGroup(v *Group) *PaymentProductCreate {
	return _c.SetGroupID(v.ID)
}

// AddOrderIDs adds the "orders" edge to the PaymentOrder entity by IDs.
func (_c *PaymentProductCreate) AddOrderIDs(ids ...int64) *PaymentProductCreate {
	_c.mutation.AddOrderIDs(ids...)
	return _c
}

// AddOrders adds the "orders" edges to the PaymentOrder entity.
func (_c *PaymentProductCreate) AddOrders(v ...*PaymentOrder) *PaymentProductCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderIDs(ids...)
}

// Mutation returns the PaymentProductMutation object of the builder.
func (_c *PaymentProductCreate) Mutation() *PaymentProductMutation {
	return _c.mutation
}

// Save creates the PaymentProduct in the database.
func (_c *PaymentProductCreate) Save(ctx context.Context) (*PaymentProduct, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentProductCreate) SaveX(ctx context.Context) *PaymentProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentProductCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentProductCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentProductCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentproduct.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentproduct.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DescriptionMd(); !ok {
		v := paymentproduct.DefaultDescriptionMd
		_c.mutation.SetDescriptionMd(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentproduct.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := paymentproduct.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := paymentproduct.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.PriceCents(); !ok {
		v := paymentproduct.DefaultPriceCents
		_c.mutation.SetPriceCents(v)
	}
	if _, ok := _c.mutation.AllowCustomAmount(); !ok {
		v := paymentproduct.DefaultAllowCustomAmount
		_c.mutation.SetAllowCustomAmount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentProductCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentProduct.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentProduct.updated_at"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "PaymentProduct.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := paymentproduct.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "PaymentProduct.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PaymentProduct.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := paymentproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PaymentProduct.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DescriptionMd(); !ok {
		return &ValidationError{Name: "description_md", err: errors.New(`ent: missing required field "PaymentProduct.description_md"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentProduct.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentproduct.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentProduct.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "PaymentProduct.sort_order"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "PaymentProduct.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := paymentproduct.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentProduct.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PriceCents(); !ok {
		return &ValidationError{Name: "price_cents", err: errors.New(`ent: missing required field "PaymentProduct.price_cents"`)}
	}
	if _, ok := _c.mutation.AllowCustomAmount(); !ok {
		return &ValidationError{Name: "allow_custom_amount", err: errors.New(`ent: missing required field "PaymentProduct.allow_custom_amount"`)}
	}
	return nil
}

func (_c *PaymentProductCreate) sqlSave(ctx context.Context) (*PaymentProduct, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentProductCreate) createSpec() (*PaymentProduct, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentProduct{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentproduct.Table, sqlgraph.NewFieldSpec(paymentproduct.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentproduct.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentproduct.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(paymentproduct.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(paymentproduct.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DescriptionMd(); ok {
		_spec.SetField(paymentproduct.FieldDescriptionMd, field.TypeString, value)
		_node.DescriptionMd = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentproduct.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(paymentproduct.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(paymentproduct.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.PriceCents(); ok {
		_spec.SetField(paymentproduct.FieldPriceCents, field.TypeInt64, value)
		_node.PriceCents = value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(paymentproduct.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = &value
	}
	if value, ok := _c.mutation.CreditBalance(); ok {
		_spec.SetField(paymentproduct.FieldCreditBalance, field.TypeFloat64, value)
		_node.CreditBalance = &value
	}
	if value, ok := _c.mutation.AllowCustomAmount(); ok {
		_spec.SetField(paymentproduct.FieldAllowCustomAmount, field.TypeBool, value)
		_node.AllowCustomAmount = value
	}
	if value, ok := _c.mutation.MinAmountCents(); ok {
		_spec.SetField(paymentproduct.FieldMinAmountCents, field.TypeInt64, value)
		_node.MinAmountCents = &value
	}
	if value, ok := _c.mutation.MaxAmountCents(); ok {
		_spec.SetField(paymentproduct.FieldMaxAmountCents, field.TypeInt64, value)
		_node.MaxAmountCents = &value
	}
	if value, ok := _c.mutation.SuggestedAmountsCents(); ok {
		_spec.SetField(paymentproduct.FieldSuggestedAmountsCents, field.TypeJSON, value)
		_node.SuggestedAmountsCents = value
	}
	if value, ok := _c.mutation.ExchangeRate(); ok {
		_spec.SetField(paymentproduct.FieldExchangeRate, field.TypeFloat64, value)
		_node.ExchangeRate = &value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentproduct.GroupTable,
			Columns: []string{paymentproduct.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentproduct.OrdersTable,
			Columns: []string{paymentproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentProduct.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentProductUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentProductCreate) OnConflict(opts ...sql.ConflictOption) *PaymentProductUpsertOne {
	_c.conflict = opts
	return &PaymentProductUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentProductCreate) OnConflictColumns(columns ...string) *PaymentProductUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentProductUpsertOne{
		create: _c,
	}
}

type (
	// PaymentProductUpsertOne is the builder for "upsert"-ing
	//  one PaymentProduct node.
	PaymentProductUpsertOne struct {
		create *PaymentProductCreate
	}

	// PaymentProductUpsert is the "OnConflict" setter.
	PaymentProductUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentProductUpsert) SetUpdatedAt(v time.Time) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateUpdatedAt() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldUpdatedAt)
	return u
}

// SetKind sets the "kind" field.
func (u *PaymentProductUpsert) SetKind(v string) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateKind() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldKind)
	return u
}

// SetName sets the "name" field.
func (u *PaymentProductUpsert) SetName(v string) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateName() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldName)
	return u
}

// SetDescriptionMd sets the "description_md" field.
func (u *PaymentProductUpsert) SetDescriptionMd(v string) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldDescriptionMd, v)
	return u
}

// UpdateDescriptionMd sets the "description_md" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateDescriptionMd() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldDescriptionMd)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentProductUpsert) SetStatus(v string) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateStatus() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldStatus)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *PaymentProductUpsert) SetSortOrder(v int) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateSortOrder() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PaymentProductUpsert) AddSortOrder(v int) *PaymentProductUpsert {
	u.Add(paymentproduct.FieldSortOrder, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *PaymentProductUpsert) SetCurrency(v string) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateCurrency() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldCurrency)
	return u
}

// SetPriceCents sets the "price_cents" field.
func (u *PaymentProductUpsert) SetPriceCents(v int64) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldPriceCents, v)
	return u
}

// UpdatePriceCents sets the "price_cents" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdatePriceCents() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldPriceCents)
	return u
}

// AddPriceCents adds v to the "price_cents" field.
func (u *PaymentProductUpsert) AddPriceCents(v int64) *PaymentProductUpsert {
	u.Add(paymentproduct.FieldPriceCents, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *PaymentProductUpsert) SetGroupID(v int64) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateGroupID() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldGroupID)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *PaymentProductUpsert) ClearGroupID() *PaymentProductUpsert {
	u.SetNull(paymentproduct.FieldGroupID)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *PaymentProductUpsert) SetValidityDays(v int) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateValidityDays() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *PaymentProductUpsert) AddValidityDays(v int) *PaymentProductUpsert {
	u.Add(paymentproduct.FieldValidityDays, v)
	return u
}

// ClearValidityDays clears the value of the "validity_days" field.
func (u *PaymentProductUpsert) ClearValidityDays() *PaymentProductUpsert {
	u.SetNull(paymentproduct.FieldValidityDays)
	return u
}

// SetCreditBalance sets the "credit_balance" field.
func (u *PaymentProductUpsert) SetCreditBalance(v float64) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldCreditBalance, v)
	return u
}

// UpdateCreditBalance sets the "credit_balance" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateCreditBalance() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldCreditBalance)
	return u
}

// AddCreditBalance adds v to the "credit_balance" field.
func (u *PaymentProductUpsert) AddCreditBalance(v float64) *PaymentProductUpsert {
	u.Add(paymentproduct.FieldCreditBalance, v)
	return u
}

// ClearCreditBalance clears the value of the "credit_balance" field.
func (u *PaymentProductUpsert) ClearCreditBalance() *PaymentProductUpsert {
	u.SetNull(paymentproduct.FieldCreditBalance)
	return u
}

// SetAllowCustomAmount sets the "allow_custom_amount" field.
func (u *PaymentProductUpsert) SetAllowCustomAmount(v bool) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldAllowCustomAmount, v)
	return u
}

// UpdateAllowCustomAmount sets the "allow_custom_amount" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateAllowCustomAmount() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldAllowCustomAmount)
	return u
}

// SetMinAmountCents sets the "min_amount_cents" field.
func (u *PaymentProductUpsert) SetMinAmountCents(v int64) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldMinAmountCents, v)
	return u
}

// UpdateMinAmountCents sets the "min_amount_cents" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateMinAmountCents() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldMinAmountCents)
	return u
}

// AddMinAmountCents adds v to the "min_amount_cents" field.
func (u *PaymentProductUpsert) AddMinAmountCents(v int64) *PaymentProductUpsert {
	u.Add(paymentproduct.FieldMinAmountCents, v)
	return u
}

// ClearMinAmountCents clears the value of the "min_amount_cents" field.
func (u *PaymentProductUpsert) ClearMinAmountCents() *PaymentProductUpsert {
	u.SetNull(paymentproduct.FieldMinAmountCents)
	return u
}

// SetMaxAmountCents sets the "max_amount_cents" field.
func (u *PaymentProductUpsert) SetMaxAmountCents(v int64) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldMaxAmountCents, v)
	return u
}

// UpdateMaxAmountCents sets the "max_amount_cents" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateMaxAmountCents() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldMaxAmountCents)
	return u
}

// AddMaxAmountCents adds v to the "max_amount_cents" field.
func (u *PaymentProductUpsert) AddMaxAmountCents(v int64) *PaymentProductUpsert {
	u.Add(paymentproduct.FieldMaxAmountCents, v)
	return u
}

// ClearMaxAmountCents clears the value of the "max_amount_cents" field.
func (u *PaymentProductUpsert) ClearMaxAmountCents() *PaymentProductUpsert {
	u.SetNull(paymentproduct.FieldMaxAmountCents)
	return u
}

// SetSuggestedAmountsCents sets the "suggested_amounts_cents" field.
func (u *PaymentProductUpsert) SetSuggestedAmountsCents(v []int64) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldSuggestedAmountsCents, v)
	return u
}

// UpdateSuggestedAmountsCents sets the "suggested_amounts_cents" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateSuggestedAmountsCents() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldSuggestedAmountsCents)
	return u
}

// ClearSuggestedAmountsCents clears the value of the "suggested_amounts_cents" field.
func (u *PaymentProductUpsert) ClearSuggestedAmountsCents() *PaymentProductUpsert {
	u.SetNull(paymentproduct.FieldSuggestedAmountsCents)
	return u
}

// SetExchangeRate sets the "exchange_rate" field.
func (u *PaymentProductUpsert) SetExchangeRate(v float64) *PaymentProductUpsert {
	u.Set(paymentproduct.FieldExchangeRate, v)
	return u
}

// UpdateExchangeRate sets the "exchange_rate" field to the value that was provided on create.
func (u *PaymentProductUpsert) UpdateExchangeRate() *PaymentProductUpsert {
	u.SetExcluded(paymentproduct.FieldExchangeRate)
	return u
}

// AddExchangeRate adds v to the "exchange_rate" field.
func (u *PaymentProductUpsert) AddExchangeRate(v float64) *PaymentProductUpsert {
	u.Add(paymentproduct.FieldExchangeRate, v)
	return u
}

// ClearExchangeRate clears the value of the "exchange_rate" field.
func (u *PaymentProductUpsert) ClearExchangeRate() *PaymentProductUpsert {
	u.SetNull(paymentproduct.FieldExchangeRate)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentProductUpsertOne) UpdateNewValues() *PaymentProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentproduct.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentProduct.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentProductUpsertOne) Ignore() *PaymentProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentProductUpsertOne) DoNothing() *PaymentProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentProductCreate.OnConflict
// documentation for more info.
func (u *PaymentProductUpsertOne) Update(set func(*PaymentProductUpsert)) *PaymentProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentProductUpsertOne) SetUpdatedAt(v time.Time) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateUpdatedAt() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKind sets the "kind" field.
func (u *PaymentProductUpsertOne) SetKind(v string) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateKind() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateKind()
	})
}

// SetName sets the "name" field.
func (u *PaymentProductUpsertOne) SetName(v string) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateName() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateName()
	})
}

// SetDescriptionMd sets the "description_md" field.
func (u *PaymentProductUpsertOne) SetDescriptionMd(v string) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetDescriptionMd(v)
	})
}

// UpdateDescriptionMd sets the "description_md" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateDescriptionMd() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateDescriptionMd()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentProductUpsertOne) SetStatus(v string) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateStatus() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *PaymentProductUpsertOne) SetSortOrder(v int) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PaymentProductUpsertOne) AddSortOrder(v int) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateSortOrder() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentProductUpsertOne) SetCurrency(v string) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateCurrency() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateCurrency()
	})
}

// SetPriceCents sets the "price_cents" field.
func (u *PaymentProductUpsertOne) SetPriceCents(v int64) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetPriceCents(v)
	})
}

// AddPriceCents adds v to the "price_cents" field.
func (u *PaymentProductUpsertOne) AddPriceCents(v int64) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddPriceCents(v)
	})
}

// UpdatePriceCents sets the "price_cents" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdatePriceCents() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdatePriceCents()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PaymentProductUpsertOne) SetGroupID(v int64) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateGroupID() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *PaymentProductUpsertOne) ClearGroupID() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearGroupID()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *PaymentProductUpsertOne) SetValidityDays(v int) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *PaymentProductUpsertOne) AddValidityDays(v int) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateValidityDays() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateValidityDays()
	})
}

// ClearValidityDays clears the value of the "validity_days" field.
func (u *PaymentProductUpsertOne) ClearValidityDays() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearValidityDays()
	})
}

// SetCreditBalance sets the "credit_balance" field.
func (u *PaymentProductUpsertOne) SetCreditBalance(v float64) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetCreditBalance(v)
	})
}

// AddCreditBalance adds v to the "credit_balance" field.
func (u *PaymentProductUpsertOne) AddCreditBalance(v float64) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddCreditBalance(v)
	})
}

// UpdateCreditBalance sets the "credit_balance" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateCreditBalance() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateCreditBalance()
	})
}

// ClearCreditBalance clears the value of the "credit_balance" field.
func (u *PaymentProductUpsertOne) ClearCreditBalance() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearCreditBalance()
	})
}

// SetAllowCustomAmount sets the "allow_custom_amount" field.
func (u *PaymentProductUpsertOne) SetAllowCustomAmount(v bool) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetAllowCustomAmount(v)
	})
}

// UpdateAllowCustomAmount sets the "allow_custom_amount" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateAllowCustomAmount() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateAllowCustomAmount()
	})
}

// SetMinAmountCents sets the "min_amount_cents" field.
func (u *PaymentProductUpsertOne) SetMinAmountCents(v int64) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetMinAmountCents(v)
	})
}

// AddMinAmountCents adds v to the "min_amount_cents" field.
func (u *PaymentProductUpsertOne) AddMinAmountCents(v int64) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddMinAmountCents(v)
	})
}

// UpdateMinAmountCents sets the "min_amount_cents" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateMinAmountCents() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateMinAmountCents()
	})
}

// ClearMinAmountCents clears the value of the "min_amount_cents" field.
func (u *PaymentProductUpsertOne) ClearMinAmountCents() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearMinAmountCents()
	})
}

// SetMaxAmountCents sets the "max_amount_cents" field.
func (u *PaymentProductUpsertOne) SetMaxAmountCents(v int64) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetMaxAmountCents(v)
	})
}

// AddMaxAmountCents adds v to the "max_amount_cents" field.
func (u *PaymentProductUpsertOne) AddMaxAmountCents(v int64) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddMaxAmountCents(v)
	})
}

// UpdateMaxAmountCents sets the "max_amount_cents" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateMaxAmountCents() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateMaxAmountCents()
	})
}

// ClearMaxAmountCents clears the value of the "max_amount_cents" field.
func (u *PaymentProductUpsertOne) ClearMaxAmountCents() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearMaxAmountCents()
	})
}

// SetSuggestedAmountsCents sets the "suggested_amounts_cents" field.
func (u *PaymentProductUpsertOne) SetSuggestedAmountsCents(v []int64) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetSuggestedAmountsCents(v)
	})
}

// UpdateSuggestedAmountsCents sets the "suggested_amounts_cents" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateSuggestedAmountsCents() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateSuggestedAmountsCents()
	})
}

// ClearSuggestedAmountsCents clears the value of the "suggested_amounts_cents" field.
func (u *PaymentProductUpsertOne) ClearSuggestedAmountsCents() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearSuggestedAmountsCents()
	})
}

// SetExchangeRate sets the "exchange_rate" field.
func (u *PaymentProductUpsertOne) SetExchangeRate(v float64) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetExchangeRate(v)
	})
}

// AddExchangeRate adds v to the "exchange_rate" field.
func (u *PaymentProductUpsertOne) AddExchangeRate(v float64) *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddExchangeRate(v)
	})
}

// UpdateExchangeRate sets the "exchange_rate" field to the value that was provided on create.
func (u *PaymentProductUpsertOne) UpdateExchangeRate() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateExchangeRate()
	})
}

// ClearExchangeRate clears the value of the "exchange_rate" field.
func (u *PaymentProductUpsertOne) ClearExchangeRate() *PaymentProductUpsertOne {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearExchangeRate()
	})
}

// Exec executes the query.
func (u *PaymentProductUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentProductCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentProductUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentProductUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentProductUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentProductCreateBulk is the builder for creating many PaymentProduct entities in bulk.
type PaymentProductCreateBulk struct {
	config
	err      error
	builders []*PaymentProductCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentProduct entities in the database.
func (_c *PaymentProductCreateBulk) Save(ctx context.Context) ([]*PaymentProduct, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentProduct, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentProductCreateBulk) SaveX(ctx context.Context) []*PaymentProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentProductCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentProductCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentProduct.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentProductUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentProductCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentProductUpsertBulk {
	_c.conflict = opts
	return &PaymentProductUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentProductCreateBulk) OnConflictColumns(columns ...string) *PaymentProductUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentProductUpsertBulk{
		create: _c,
	}
}

// PaymentProductUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentProduct nodes.
type PaymentProductUpsertBulk struct {
	create *PaymentProductCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentProductUpsertBulk) UpdateNewValues() *PaymentProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentproduct.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentProduct.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentProductUpsertBulk) Ignore() *PaymentProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentProductUpsertBulk) DoNothing() *PaymentProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentProductCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentProductUpsertBulk) Update(set func(*PaymentProductUpsert)) *PaymentProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentProductUpsertBulk) SetUpdatedAt(v time.Time) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateUpdatedAt() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKind sets the "kind" field.
func (u *PaymentProductUpsertBulk) SetKind(v string) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateKind() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateKind()
	})
}

// SetName sets the "name" field.
func (u *PaymentProductUpsertBulk) SetName(v string) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateName() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateName()
	})
}

// SetDescriptionMd sets the "description_md" field.
func (u *PaymentProductUpsertBulk) SetDescriptionMd(v string) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetDescriptionMd(v)
	})
}

// UpdateDescriptionMd sets the "description_md" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateDescriptionMd() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateDescriptionMd()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentProductUpsertBulk) SetStatus(v string) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateStatus() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *PaymentProductUpsertBulk) SetSortOrder(v int) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PaymentProductUpsertBulk) AddSortOrder(v int) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateSortOrder() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentProductUpsertBulk) SetCurrency(v string) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateCurrency() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateCurrency()
	})
}

// SetPriceCents sets the "price_cents" field.
func (u *PaymentProductUpsertBulk) SetPriceCents(v int64) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetPriceCents(v)
	})
}

// AddPriceCents adds v to the "price_cents" field.
func (u *PaymentProductUpsertBulk) AddPriceCents(v int64) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddPriceCents(v)
	})
}

// UpdatePriceCents sets the "price_cents" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdatePriceCents() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdatePriceCents()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PaymentProductUpsertBulk) SetGroupID(v int64) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateGroupID() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *PaymentProductUpsertBulk) ClearGroupID() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearGroupID()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *PaymentProductUpsertBulk) SetValidityDays(v int) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *PaymentProductUpsertBulk) AddValidityDays(v int) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateValidityDays() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateValidityDays()
	})
}

// ClearValidityDays clears the value of the "validity_days" field.
func (u *PaymentProductUpsertBulk) ClearValidityDays() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearValidityDays()
	})
}

// SetCreditBalance sets the "credit_balance" field.
func (u *PaymentProductUpsertBulk) SetCreditBalance(v float64) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetCreditBalance(v)
	})
}

// AddCreditBalance adds v to the "credit_balance" field.
func (u *PaymentProductUpsertBulk) AddCreditBalance(v float64) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddCreditBalance(v)
	})
}

// UpdateCreditBalance sets the "credit_balance" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateCreditBalance() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateCreditBalance()
	})
}

// ClearCreditBalance clears the value of the "credit_balance" field.
func (u *PaymentProductUpsertBulk) ClearCreditBalance() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearCreditBalance()
	})
}

// SetAllowCustomAmount sets the "allow_custom_amount" field.
func (u *PaymentProductUpsertBulk) SetAllowCustomAmount(v bool) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetAllowCustomAmount(v)
	})
}

// UpdateAllowCustomAmount sets the "allow_custom_amount" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateAllowCustomAmount() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateAllowCustomAmount()
	})
}

// SetMinAmountCents sets the "min_amount_cents" field.
func (u *PaymentProductUpsertBulk) SetMinAmountCents(v int64) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetMinAmountCents(v)
	})
}

// AddMinAmountCents adds v to the "min_amount_cents" field.
func (u *PaymentProductUpsertBulk) AddMinAmountCents(v int64) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddMinAmountCents(v)
	})
}

// UpdateMinAmountCents sets the "min_amount_cents" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateMinAmountCents() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateMinAmountCents()
	})
}

// ClearMinAmountCents clears the value of the "min_amount_cents" field.
func (u *PaymentProductUpsertBulk) ClearMinAmountCents() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearMinAmountCents()
	})
}

// SetMaxAmountCents sets the "max_amount_cents" field.
func (u *PaymentProductUpsertBulk) SetMaxAmountCents(v int64) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetMaxAmountCents(v)
	})
}

// AddMaxAmountCents adds v to the "max_amount_cents" field.
func (u *PaymentProductUpsertBulk) AddMaxAmountCents(v int64) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddMaxAmountCents(v)
	})
}

// UpdateMaxAmountCents sets the "max_amount_cents" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateMaxAmountCents() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateMaxAmountCents()
	})
}

// ClearMaxAmountCents clears the value of the "max_amount_cents" field.
func (u *PaymentProductUpsertBulk) ClearMaxAmountCents() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearMaxAmountCents()
	})
}

// SetSuggestedAmountsCents sets the "suggested_amounts_cents" field.
func (u *PaymentProductUpsertBulk) SetSuggestedAmountsCents(v []int64) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetSuggestedAmountsCents(v)
	})
}

// UpdateSuggestedAmountsCents sets the "suggested_amounts_cents" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateSuggestedAmountsCents() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateSuggestedAmountsCents()
	})
}

// ClearSuggestedAmountsCents clears the value of the "suggested_amounts_cents" field.
func (u *PaymentProductUpsertBulk) ClearSuggestedAmountsCents() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearSuggestedAmountsCents()
	})
}

// SetExchangeRate sets the "exchange_rate" field.
func (u *PaymentProductUpsertBulk) SetExchangeRate(v float64) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.SetExchangeRate(v)
	})
}

// AddExchangeRate adds v to the "exchange_rate" field.
func (u *PaymentProductUpsertBulk) AddExchangeRate(v float64) *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.AddExchangeRate(v)
	})
}

// UpdateExchangeRate sets the "exchange_rate" field to the value that was provided on create.
func (u *PaymentProductUpsertBulk) UpdateExchangeRate() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.UpdateExchangeRate()
	})
}

// ClearExchangeRate clears the value of the "exchange_rate" field.
func (u *PaymentProductUpsertBulk) ClearExchangeRate() *PaymentProductUpsertBulk {
	return u.Update(func(s *PaymentProductUpsert) {
		s.ClearExchangeRate()
	})
}

// Exec executes the query.
func (u *PaymentProductUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentProductCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentProductCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentProductUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
