// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/paymentproduct"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentProductUpdate is the builder for updating PaymentProduct entities.
type PaymentProductUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentProductMutation
}

// Where appends a list predicates to the PaymentProductUpdate builder.
func (_u *PaymentProductUpdate) Where(ps ...predicate.PaymentProduct) *PaymentProductUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentProductUpdate) SetUpdatedAt(v time.Time) *PaymentProductUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *PaymentProductUpdate) SetKind(v string) *PaymentProductUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillableKind(v *string) *PaymentProductUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PaymentProductUpdate) SetName(v string) *PaymentProductUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillableName(v *string) *PaymentProductUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescriptionMd sets the "description_md" field.
func (_u *PaymentProductUpdate) SetDescriptionMd(v string) *PaymentProductUpdate {
	_u.mutation.SetDescriptionMd(v)
	return _u
}

// SetNillableDescriptionMd sets the "description_md" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillableDescriptionMd(v *string) *PaymentProductUpdate {
	if v != nil {
		_u.SetDescriptionMd(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentProductUpdate) SetStatus(v string) *PaymentProductUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillableStatus(v *string) *PaymentProductUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *PaymentProductUpdate) SetSortOrder(v int) *PaymentProductUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillableSortOrder(v *int) *PaymentProductUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *PaymentProductUpdate) AddSortOrder(v int) *PaymentProductUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentProductUpdate) SetCurrency(v string) *PaymentProductUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillableCurrency(v *string) *PaymentProductUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetPriceCents sets the "price_cents" field.
func (_u *PaymentProductUpdate) SetPriceCents(v int64) *PaymentProductUpdate {
	_u.mutation.ResetPriceCents()
	_u.mutation.SetPriceCents(v)
	return _u
}

// SetNillablePriceCents sets the "price_cents" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillablePriceCents(v *int64) *PaymentProductUpdate {
	if v != nil {
		_u.SetPriceCents(*v)
	}
	return _u
}

// AddPriceCents adds value to the "price_cents" field.
func (_u *PaymentProductUpdate) AddPriceCents(v int64) *PaymentProductUpdate {
	_u.mutation.AddPriceCents(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PaymentProductUpdate) SetGroupID(v int64) *PaymentProductUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillableGroupID(v *int64) *PaymentProductUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *PaymentProductUpdate) ClearGroupID() *PaymentProductUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *PaymentProductUpdate) SetValidityDays(v int) *PaymentProductUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillableValidityDays(v *int) *PaymentProductUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *PaymentProductUpdate) AddValidityDays(v int) *PaymentProductUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// ClearValidityDays clears the value of the "validity_days" field.
func (_u *PaymentProductUpdate) ClearValidityDays() *PaymentProductUpdate {
	_u.mutation.ClearValidityDays()
	return _u
}

// SetCreditBalance sets the "credit_balance" field.
func (_u *PaymentProductUpdate) SetCreditBalance(v float64) *PaymentProductUpdate {
	_u.mutation.ResetCreditBalance()
	_u.mutation.SetCreditBalance(v)
	return _u
}

// SetNillableCreditBalance sets the "credit_balance" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillableCreditBalance(v *float64) *PaymentProductUpdate {
	if v != nil {
		_u.SetCreditBalance(*v)
	}
	return _u
}

// AddCreditBalance adds value to the "credit_balance" field.
func (_u *PaymentProductUpdate) AddCreditBalance(v float64) *PaymentProductUpdate {
	_u.mutation.AddCreditBalance(v)
	return _u
}

// ClearCreditBalance clears the value of the "credit_balance" field.
func (_u *PaymentProductUpdate) ClearCreditBalance() *PaymentProductUpdate {
	_u.mutation.ClearCreditBalance()
	return _u
}

// SetAllowCustomAmount sets the "allow_custom_amount" field.
func (_u *PaymentProductUpdate) SetAllowCustomAmount(v bool) *PaymentProductUpdate {
	_u.mutation.SetAllowCustomAmount(v)
	return _u
}

// SetNillableAllowCustomAmount sets the "allow_custom_amount" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillableAllowCustomAmount(v *bool) *PaymentProductUpdate {
	if v != nil {
		_u.SetAllowCustomAmount(*v)
	}
	return _u
}

// SetMinAmountCents sets the "min_amount_cents" field.
func (_u *PaymentProductUpdate) SetMinAmountCents(v int64) *PaymentProductUpdate {
	_u.mutation.ResetMinAmountCents()
	_u.mutation.SetMinAmountCents(v)
	return _u
}

// SetNillableMinAmountCents sets the "min_amount_cents" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillableMinAmountCents(v *int64) *PaymentProductUpdate {
	if v != nil {
		_u.SetMinAmountCents(*v)
	}
	return _u
}

// AddMinAmountCents adds value to the "min_amount_cents" field.
func (_u *PaymentProductUpdate) AddMinAmountCents(v int64) *PaymentProductUpdate {
	_u.mutation.AddMinAmountCents(v)
	return _u
}

// ClearMinAmountCents clears the value of the "min_amount_cents" field.
func (_u *PaymentProductUpdate) ClearMinAmountCents() *PaymentProductUpdate {
	_u.mutation.ClearMinAmountCents()
	return _u
}

// SetMaxAmountCents sets the "max_amount_cents" field.
func (_u *PaymentProductUpdate) SetMaxAmountCents(v int64) *PaymentProductUpdate {
	_u.mutation.ResetMaxAmountCents()
	_u.mutation.SetMaxAmountCents(v)
	return _u
}

// SetNillableMaxAmountCents sets the "max_amount_cents" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillableMaxAmountCents(v *int64) *PaymentProductUpdate {
	if v != nil {
		_u.SetMaxAmountCents(*v)
	}
	return _u
}

// AddMaxAmountCents adds value to the "max_amount_cents" field.
func (_u *PaymentProductUpdate) AddMaxAmountCents(v int64) *PaymentProductUpdate {
	_u.mutation.AddMaxAmountCents(v)
	return _u
}

// ClearMaxAmountCents clears the value of the "max_amount_cents" field.
func (_u *PaymentProductUpdate) ClearMaxAmountCents() *PaymentProductUpdate {
	_u.mutation.ClearMaxAmountCents()
	return _u
}

// SetSuggestedAmountsCents sets the "suggested_amounts_cents" field.
func (_u *PaymentProductUpdate) SetSuggestedAmountsCents(v []int64) *PaymentProductUpdate {
	_u.mutation.SetSuggestedAmountsCents(v)
	return _u
}

// AppendSuggestedAmountsCents appends value to the "suggested_amounts_cents" field.
func (_u *PaymentProductUpdate) AppendSuggestedAmountsCents(v []int64) *PaymentProductUpdate {
	_u.mutation.AppendSuggestedAmountsCents(v)
	return _u
}

// ClearSuggestedAmountsCents clears the value of the "suggested_amounts_cents" field.
func (_u *PaymentProductUpdate) ClearSuggestedAmountsCents() *PaymentProductUpdate {
	_u.mutation.ClearSuggestedAmountsCents()
	return _u
}

// SetExchangeRate sets the "exchange_rate" field.
func (_u *PaymentProductUpdate) SetExchangeRate(v float64) *PaymentProductUpdate {
	_u.mutation.ResetExchangeRate()
	_u.mutation.SetExchangeRate(v)
	return _u
}

// SetNillableExchangeRate sets the "exchange_rate" field if the given value is not nil.
func (_u *PaymentProductUpdate) SetNillableExchangeRate(v *float64) *PaymentProductUpdate {
	if v != nil {
		_u.SetExchangeRate(*v)
	}
	return _u
}

// AddExchangeRate adds value to the "exchange_rate" field.
func (_u *PaymentProductUpdate) AddExchangeRate(v float64) *PaymentProductUpdate {
	_u.mutation.AddExchangeRate(v)
	return _u
}

// ClearExchangeRate clears the value of the "exchange_rate" field.
func (_u *PaymentProductUpdate) ClearExchangeRate() *PaymentProductUpdate {
	_u.mutation.ClearExchangeRate()
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *PaymentProductUpdate) SetGroup(v *Group) *PaymentProductUpdate {
	return _u.SetGroupID(v.ID)
}

// AddOrderIDs adds the "orders" edge to the PaymentOrder entity by IDs.
func (_u *PaymentProductUpdate) AddOrderIDs(ids ...int64) *PaymentProductUpdate {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the PaymentOrder entity.
func (_u *PaymentProductUpdate) AddOrders(v ...*PaymentOrder) *PaymentProductUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the PaymentProductMutation object of the builder.
func (_u *PaymentProductUpdate) Mutation() *PaymentProductMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *PaymentProductUpdate) ClearGroup() *PaymentProductUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearOrders clears all "orders" edges to the PaymentOrder entity.
func (_u *PaymentProductUpdate) ClearOrders() *PaymentProductUpdate {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to PaymentOrder entities by IDs.
func (_u *PaymentProductUpdate) RemoveOrderIDs(ids ...int64) *PaymentProductUpdate {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to PaymentOrder entities.
func (_u *PaymentProductUpdate) RemoveOrders(v ...*PaymentOrder) *PaymentProductUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentProductUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentProductUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentProductUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentProductUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentProductUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentproduct.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentProductUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := paymentproduct.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "PaymentProduct.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := paymentproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PaymentProduct.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentproduct.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentProduct.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentproduct.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentProduct.currency": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentProductUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentproduct.Table, paymentproduct.Columns, sqlgraph.NewFieldSpec(paymentproduct.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentproduct.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(paymentproduct.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(paymentproduct.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DescriptionMd(); ok {
		_spec.SetField(paymentproduct.FieldDescriptionMd, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentproduct.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(paymentproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(paymentproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentproduct.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceCents(); ok {
		_spec.SetField(paymentproduct.FieldPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceCents(); ok {
		_spec.AddField(paymentproduct.FieldPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(paymentproduct.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(paymentproduct.FieldValidityDays, field.TypeInt, value)
	}
	if _u.mutation.ValidityDaysCleared() {
		_spec.ClearField(paymentproduct.FieldValidityDays, field.TypeInt)
	}
	if value, ok := _u.mutation.CreditBalance(); ok {
		_spec.SetField(paymentproduct.FieldCreditBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditBalance(); ok {
		_spec.AddField(paymentproduct.FieldCreditBalance, field.TypeFloat64, value)
	}
	if _u.mutation.CreditBalanceCleared() {
		_spec.ClearField(paymentproduct.FieldCreditBalance, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AllowCustomAmount(); ok {
		_spec.SetField(paymentproduct.FieldAllowCustomAmount, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MinAmountCents(); ok {
		_spec.SetField(paymentproduct.FieldMinAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMinAmountCents(); ok {
		_spec.AddField(paymentproduct.FieldMinAmountCents, field.TypeInt64, value)
	}
	if _u.mutation.MinAmountCentsCleared() {
		_spec.ClearField(paymentproduct.FieldMinAmountCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.MaxAmountCents(); ok {
		_spec.SetField(paymentproduct.FieldMaxAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaxAmountCents(); ok {
		_spec.AddField(paymentproduct.FieldMaxAmountCents, field.TypeInt64, value)
	}
	if _u.mutation.MaxAmountCentsCleared() {
		_spec.ClearField(paymentproduct.FieldMaxAmountCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.SuggestedAmountsCents(); ok {
		_spec.SetField(paymentproduct.FieldSuggestedAmountsCents, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSuggestedAmountsCents(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, paymentproduct.FieldSuggestedAmountsCents, value)
		})
	}
	if _u.mutation.SuggestedAmountsCentsCleared() {
		_spec.ClearField(paymentproduct.FieldSuggestedAmountsCents, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExchangeRate(); ok {
		_spec.SetField(paymentproduct.FieldExchangeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExchangeRate(); ok {
		_spec.AddField(paymentproduct.FieldExchangeRate, field.TypeFloat64, value)
	}
	if _u.mutation.ExchangeRateCleared() {
		_spec.ClearField(paymentproduct.FieldExchangeRate, field.TypeFloat64)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentproduct.GroupTable,
			Columns: []string{paymentproduct.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentproduct.GroupTable,
			Columns: []string{paymentproduct.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentproduct.OrdersTable,
			Columns: []string{paymentproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentproduct.OrdersTable,
			Columns: []string{paymentproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentproduct.OrdersTable,
			Columns: []string{paymentproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentProductUpdateOne is the builder for updating a single PaymentProduct entity.
type PaymentProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentProductMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentProductUpdateOne) SetUpdatedAt(v time.Time) *PaymentProductUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *PaymentProductUpdateOne) SetKind(v string) *PaymentProductUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillableKind(v *string) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PaymentProductUpdateOne) SetName(v string) *PaymentProductUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillableName(v *string) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescriptionMd sets the "description_md" field.
func (_u *PaymentProductUpdateOne) SetDescriptionMd(v string) *PaymentProductUpdateOne {
	_u.mutation.SetDescriptionMd(v)
	return _u
}

// SetNillableDescriptionMd sets the "description_md" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillableDescriptionMd(v *string) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetDescriptionMd(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentProductUpdateOne) SetStatus(v string) *PaymentProductUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillableStatus(v *string) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *PaymentProductUpdateOne) SetSortOrder(v int) *PaymentProductUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillableSortOrder(v *int) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *PaymentProductUpdateOne) AddSortOrder(v int) *PaymentProductUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentProductUpdateOne) SetCurrency(v string) *PaymentProductUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillableCurrency(v *string) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetPriceCents sets the "price_cents" field.
func (_u *PaymentProductUpdateOne) SetPriceCents(v int64) *PaymentProductUpdateOne {
	_u.mutation.ResetPriceCents()
	_u.mutation.SetPriceCents(v)
	return _u
}

// SetNillablePriceCents sets the "price_cents" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillablePriceCents(v *int64) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetPriceCents(*v)
	}
	return _u
}

// AddPriceCents adds value to the "price_cents" field.
func (_u *PaymentProductUpdateOne) AddPriceCents(v int64) *PaymentProductUpdateOne {
	_u.mutation.AddPriceCents(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PaymentProductUpdateOne) SetGroupID(v int64) *PaymentProductUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillableGroupID(v *int64) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *PaymentProductUpdateOne) ClearGroupID() *PaymentProductUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *PaymentProductUpdateOne) SetValidityDays(v int) *PaymentProductUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillableValidityDays(v *int) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *PaymentProductUpdateOne) AddValidityDays(v int) *PaymentProductUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// ClearValidityDays clears the value of the "validity_days" field.
func (_u *PaymentProductUpdateOne) ClearValidityDays() *PaymentProductUpdateOne {
	_u.mutation.ClearValidityDays()
	return _u
}

// SetCreditBalance sets the "credit_balance" field.
func (_u *PaymentProductUpdateOne) SetCreditBalance(v float64) *PaymentProductUpdateOne {
	_u.mutation.ResetCreditBalance()
	_u.mutation.SetCreditBalance(v)
	return _u
}

// SetNillableCreditBalance sets the "credit_balance" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillableCreditBalance(v *float64) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetCreditBalance(*v)
	}
	return _u
}

// AddCreditBalance adds value to the "credit_balance" field.
func (_u *PaymentProductUpdateOne) AddCreditBalance(v float64) *PaymentProductUpdateOne {
	_u.mutation.AddCreditBalance(v)
	return _u
}

// ClearCreditBalance clears the value of the "credit_balance" field.
func (_u *PaymentProductUpdateOne) ClearCreditBalance() *PaymentProductUpdateOne {
	_u.mutation.ClearCreditBalance()
	return _u
}

// SetAllowCustomAmount sets the "allow_custom_amount" field.
func (_u *PaymentProductUpdateOne) SetAllowCustomAmount(v bool) *PaymentProductUpdateOne {
	_u.mutation.SetAllowCustomAmount(v)
	return _u
}

// SetNillableAllowCustomAmount sets the "allow_custom_amount" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillableAllowCustomAmount(v *bool) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetAllowCustomAmount(*v)
	}
	return _u
}

// SetMinAmountCents sets the "min_amount_cents" field.
func (_u *PaymentProductUpdateOne) SetMinAmountCents(v int64) *PaymentProductUpdateOne {
	_u.mutation.ResetMinAmountCents()
	_u.mutation.SetMinAmountCents(v)
	return _u
}

// SetNillableMinAmountCents sets the "min_amount_cents" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillableMinAmountCents(v *int64) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetMinAmountCents(*v)
	}
	return _u
}

// AddMinAmountCents adds value to the "min_amount_cents" field.
func (_u *PaymentProductUpdateOne) AddMinAmountCents(v int64) *PaymentProductUpdateOne {
	_u.mutation.AddMinAmountCents(v)
	return _u
}

// ClearMinAmountCents clears the value of the "min_amount_cents" field.
func (_u *PaymentProductUpdateOne) ClearMinAmountCents() *PaymentProductUpdateOne {
	_u.mutation.ClearMinAmountCents()
	return _u
}

// SetMaxAmountCents sets the "max_amount_cents" field.
func (_u *PaymentProductUpdateOne) SetMaxAmountCents(v int64) *PaymentProductUpdateOne {
	_u.mutation.ResetMaxAmountCents()
	_u.mutation.SetMaxAmountCents(v)
	return _u
}

// SetNillableMaxAmountCents sets the "max_amount_cents" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillableMaxAmountCents(v *int64) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetMaxAmountCents(*v)
	}
	return _u
}

// AddMaxAmountCents adds value to the "max_amount_cents" field.
func (_u *PaymentProductUpdateOne) AddMaxAmountCents(v int64) *PaymentProductUpdateOne {
	_u.mutation.AddMaxAmountCents(v)
	return _u
}

// ClearMaxAmountCents clears the value of the "max_amount_cents" field.
func (_u *PaymentProductUpdateOne) ClearMaxAmountCents() *PaymentProductUpdateOne {
	_u.mutation.ClearMaxAmountCents()
	return _u
}

// SetSuggestedAmountsCents sets the "suggested_amounts_cents" field.
func (_u *PaymentProductUpdateOne) SetSuggestedAmountsCents(v []int64) *PaymentProductUpdateOne {
	_u.mutation.SetSuggestedAmountsCents(v)
	return _u
}

// AppendSuggestedAmountsCents appends value to the "suggested_amounts_cents" field.
func (_u *PaymentProductUpdateOne) AppendSuggestedAmountsCents(v []int64) *PaymentProductUpdateOne {
	_u.mutation.AppendSuggestedAmountsCents(v)
	return _u
}

// ClearSuggestedAmountsCents clears the value of the "suggested_amounts_cents" field.
func (_u *PaymentProductUpdateOne) ClearSuggestedAmountsCents() *PaymentProductUpdateOne {
	_u.mutation.ClearSuggestedAmountsCents()
	return _u
}

// SetExchangeRate sets the "exchange_rate" field.
func (_u *PaymentProductUpdateOne) SetExchangeRate(v float64) *PaymentProductUpdateOne {
	_u.mutation.ResetExchangeRate()
	_u.mutation.SetExchangeRate(v)
	return _u
}

// SetNillableExchangeRate sets the "exchange_rate" field if the given value is not nil.
func (_u *PaymentProductUpdateOne) SetNillableExchangeRate(v *float64) *PaymentProductUpdateOne {
	if v != nil {
		_u.SetExchangeRate(*v)
	}
	return _u
}

// AddExchangeRate adds value to the "exchange_rate" field.
func (_u *PaymentProductUpdateOne) AddExchangeRate(v float64) *PaymentProductUpdateOne {
	_u.mutation.AddExchangeRate(v)
	return _u
}

// ClearExchangeRate clears the value of the "exchange_rate" field.
func (_u *PaymentProductUpdateOne) ClearExchangeRate() *PaymentProductUpdateOne {
	_u.mutation.ClearExchangeRate()
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *PaymentProductUpdateOne) SetGroup(v *Group) *PaymentProductUpdateOne {
	return _u.SetGroupID(v.ID)
}

// AddOrderIDs adds the "orders" edge to the PaymentOrder entity by IDs.
func (_u *PaymentProductUpdateOne) AddOrderIDs(ids ...int64) *PaymentProductUpdateOne {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the PaymentOrder entity.
func (_u *PaymentProductUpdateOne) AddOrders(v ...*PaymentOrder) *PaymentProductUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the PaymentProductMutation object of the builder.
func (_u *PaymentProductUpdateOne) Mutation() *PaymentProductMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *PaymentProductUpdateOne) ClearGroup() *PaymentProductUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearOrders clears all "orders" edges to the PaymentOrder entity.
func (_u *PaymentProductUpdateOne) ClearOrders() *PaymentProductUpdateOne {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to PaymentOrder entities by IDs.
func (_u *PaymentProductUpdateOne) RemoveOrderIDs(ids ...int64) *PaymentProductUpdateOne {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to PaymentOrder entities.
func (_u *PaymentProductUpdateOne) RemoveOrders(v ...*PaymentOrder) *PaymentProductUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Where appends a list predicates to the PaymentProductUpdate builder.
func (_u *PaymentProductUpdateOne) Where(ps ...predicate.PaymentProduct) *PaymentProductUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentProductUpdateOne) Select(field string, fields ...string) *PaymentProductUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentProduct entity.
func (_u *PaymentProductUpdateOne) Save(ctx context.Context) (*PaymentProduct, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentProductUpdateOne) SaveX(ctx context.Context) *PaymentProduct {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentProductUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentProductUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentProductUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentproduct.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentProductUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := paymentproduct.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "PaymentProduct.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := paymentproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PaymentProduct.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentproduct.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentProduct.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentproduct.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentProduct.currency": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentProductUpdateOne) sqlSave(ctx context.Context) (_node *PaymentProduct, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentproduct.Table, paymentproduct.Columns, sqlgraph.NewFieldSpec(paymentproduct.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentProduct.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentproduct.FieldID)
		for _, f := range fields {
			if !paymentproduct.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentproduct.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentproduct.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(paymentproduct.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(paymentproduct.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DescriptionMd(); ok {
		_spec.SetField(paymentproduct.FieldDescriptionMd, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentproduct.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(paymentproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(paymentproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentproduct.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceCents(); ok {
		_spec.SetField(paymentproduct.FieldPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceCents(); ok {
		_spec.AddField(paymentproduct.FieldPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(paymentproduct.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(paymentproduct.FieldValidityDays, field.TypeInt, value)
	}
	if _u.mutation.ValidityDaysCleared() {
		_spec.ClearField(paymentproduct.FieldValidityDays, field.TypeInt)
	}
	if value, ok := _u.mutation.CreditBalance(); ok {
		_spec.SetField(paymentproduct.FieldCreditBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditBalance(); ok {
		_spec.AddField(paymentproduct.FieldCreditBalance, field.TypeFloat64, value)
	}
	if _u.mutation.CreditBalanceCleared() {
		_spec.ClearField(paymentproduct.FieldCreditBalance, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AllowCustomAmount(); ok {
		_spec.SetField(paymentproduct.FieldAllowCustomAmount, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MinAmountCents(); ok {
		_spec.SetField(paymentproduct.FieldMinAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMinAmountCents(); ok {
		_spec.AddField(paymentproduct.FieldMinAmountCents, field.TypeInt64, value)
	}
	if _u.mutation.MinAmountCentsCleared() {
		_spec.ClearField(paymentproduct.FieldMinAmountCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.MaxAmountCents(); ok {
		_spec.SetField(paymentproduct.FieldMaxAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaxAmountCents(); ok {
		_spec.AddField(paymentproduct.FieldMaxAmountCents, field.TypeInt64, value)
	}
	if _u.mutation.MaxAmountCentsCleared() {
		_spec.ClearField(paymentproduct.FieldMaxAmountCents, field.TypeInt64)
	}
	if value, ok := _u.mutation.SuggestedAmountsCents(); ok {
		_spec.SetField(paymentproduct.FieldSuggestedAmountsCents, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSuggestedAmountsCents(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, paymentproduct.FieldSuggestedAmountsCents, value)
		})
	}
	if _u.mutation.SuggestedAmountsCentsCleared() {
		_spec.ClearField(paymentproduct.FieldSuggestedAmountsCents, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExchangeRate(); ok {
		_spec.SetField(paymentproduct.FieldExchangeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExchangeRate(); ok {
		_spec.AddField(paymentproduct.FieldExchangeRate, field.TypeFloat64, value)
	}
	if _u.mutation.ExchangeRateCleared() {
		_spec.ClearField(paymentproduct.FieldExchangeRate, field.TypeFloat64)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentproduct.GroupTable,
			Columns: []string{paymentproduct.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentproduct.GroupTable,
			Columns: []string{paymentproduct.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentproduct.OrdersTable,
			Columns: []string{paymentproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentproduct.OrdersTable,
			Columns: []string{paymentproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentproduct.OrdersTable,
			Columns: []string{paymentproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentProduct{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
