// Code generated by ent, DO NOT EDIT.

package paymentnotification

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentnotification type in the database.
	Label = "payment_notification"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldEventID holds the string denoting the event_id field in the database.
	FieldEventID = "event_id"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldProviderTradeNo holds the string denoting the provider_trade_no field in the database.
	FieldProviderTradeNo = "provider_trade_no"
	// FieldAmountCents holds the string denoting the amount_cents field in the database.
	FieldAmountCents = "amount_cents"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldVerified holds the string denoting the verified field in the database.
	FieldVerified = "verified"
	// FieldProcessed holds the string denoting the processed field in the database.
	FieldProcessed = "processed"
	// FieldProcessError holds the string denoting the process_error field in the database.
	FieldProcessError = "process_error"
	// FieldRawBody holds the string denoting the raw_body field in the database.
	FieldRawBody = "raw_body"
	// FieldReceivedAt holds the string denoting the received_at field in the database.
	FieldReceivedAt = "received_at"
	// Table holds the table name of the paymentnotification in the database.
	Table = "payment_notifications"
)

// Columns holds all SQL columns for paymentnotification fields.
var Columns = []string{
	FieldID,
	FieldProvider,
	FieldEventID,
	FieldOrderNo,
	FieldProviderTradeNo,
	FieldAmountCents,
	FieldCurrency,
	FieldVerified,
	FieldProcessed,
	FieldProcessError,
	FieldRawBody,
	FieldReceivedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// EventIDValidator is a validator for the "event_id" field. It is called by the builders before save.
	EventIDValidator func(string) error
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultVerified holds the default value on creation for the "verified" field.
	DefaultVerified bool
	// DefaultProcessed holds the default value on creation for the "processed" field.
	DefaultProcessed bool
	// RawBodyValidator is a validator for the "raw_body" field. It is called by the builders before save.
	RawBodyValidator func(string) error
	// DefaultReceivedAt holds the default value on creation for the "received_at" field.
	DefaultReceivedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentNotification queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByEventID orders the results by the event_id field.
func ByEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventID, opts...).ToFunc()
}

// ByOrderNo orders the results by the order_no field.
func ByOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderNo, opts...).ToFunc()
}

// ByProviderTradeNo orders the results by the provider_trade_no field.
func ByProviderTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderTradeNo, opts...).ToFunc()
}

// ByAmountCents orders the results by the amount_cents field.
func ByAmountCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountCents, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByVerified orders the results by the verified field.
func ByVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerified, opts...).ToFunc()
}

// ByProcessed orders the results by the processed field.
func ByProcessed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessed, opts...).ToFunc()
}

// ByProcessError orders the results by the process_error field.
func ByProcessError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessError, opts...).ToFunc()
}

// ByRawBody orders the results by the raw_body field.
func ByRawBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawBody, opts...).ToFunc()
}

// ByReceivedAt orders the results by the received_at field.
func ByReceivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivedAt, opts...).ToFunc()
}
