// Code generated by ent, DO NOT EDIT.

package paymentnotification

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldProvider, v))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldEventID, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldOrderNo, v))
}

// ProviderTradeNo applies equality check predicate on the "provider_trade_no" field. It's identical to ProviderTradeNoEQ.
func ProviderTradeNo(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldProviderTradeNo, v))
}

// AmountCents applies equality check predicate on the "amount_cents" field. It's identical to AmountCentsEQ.
func AmountCents(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldAmountCents, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldCurrency, v))
}

// Verified applies equality check predicate on the "verified" field. It's identical to VerifiedEQ.
func Verified(v bool) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldVerified, v))
}

// Processed applies equality check predicate on the "processed" field. It's identical to ProcessedEQ.
func Processed(v bool) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldProcessed, v))
}

// ProcessError applies equality check predicate on the "process_error" field. It's identical to ProcessErrorEQ.
func ProcessError(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldProcessError, v))
}

// RawBody applies equality check predicate on the "raw_body" field. It's identical to RawBodyEQ.
func RawBody(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldRawBody, v))
}

// ReceivedAt applies equality check predicate on the "received_at" field. It's identical to ReceivedAtEQ.
func ReceivedAt(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldReceivedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContainsFold(FieldProvider, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldEventID, vs...))
}

// EventIDGT applies the GT predicate on the "event_id" field.
func EventIDGT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldEventID, v))
}

// EventIDGTE applies the GTE predicate on the "event_id" field.
func EventIDGTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldEventID, v))
}

// EventIDLT applies the LT predicate on the "event_id" field.
func EventIDLT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldEventID, v))
}

// EventIDLTE applies the LTE predicate on the "event_id" field.
func EventIDLTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldEventID, v))
}

// EventIDContains applies the Contains predicate on the "event_id" field.
func EventIDContains(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContains(FieldEventID, v))
}

// EventIDHasPrefix applies the HasPrefix predicate on the "event_id" field.
func EventIDHasPrefix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasPrefix(FieldEventID, v))
}

// EventIDHasSuffix applies the HasSuffix predicate on the "event_id" field.
func EventIDHasSuffix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasSuffix(FieldEventID, v))
}

// EventIDEqualFold applies the EqualFold predicate on the "event_id" field.
func EventIDEqualFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEqualFold(FieldEventID, v))
}

// EventIDContainsFold applies the ContainsFold predicate on the "event_id" field.
func EventIDContainsFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContainsFold(FieldEventID, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoIsNil applies the IsNil predicate on the "order_no" field.
func OrderNoIsNil() predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIsNull(FieldOrderNo))
}

// OrderNoNotNil applies the NotNil predicate on the "order_no" field.
func OrderNoNotNil() predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotNull(FieldOrderNo))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContainsFold(FieldOrderNo, v))
}

// ProviderTradeNoEQ applies the EQ predicate on the "provider_trade_no" field.
func ProviderTradeNoEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldProviderTradeNo, v))
}

// ProviderTradeNoNEQ applies the NEQ predicate on the "provider_trade_no" field.
func ProviderTradeNoNEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldProviderTradeNo, v))
}

// ProviderTradeNoIn applies the In predicate on the "provider_trade_no" field.
func ProviderTradeNoIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldProviderTradeNo, vs...))
}

// ProviderTradeNoNotIn applies the NotIn predicate on the "provider_trade_no" field.
func ProviderTradeNoNotIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldProviderTradeNo, vs...))
}

// ProviderTradeNoGT applies the GT predicate on the "provider_trade_no" field.
func ProviderTradeNoGT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldProviderTradeNo, v))
}

// ProviderTradeNoGTE applies the GTE predicate on the "provider_trade_no" field.
func ProviderTradeNoGTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldProviderTradeNo, v))
}

// ProviderTradeNoLT applies the LT predicate on the "provider_trade_no" field.
func ProviderTradeNoLT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldProviderTradeNo, v))
}

// ProviderTradeNoLTE applies the LTE predicate on the "provider_trade_no" field.
func ProviderTradeNoLTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldProviderTradeNo, v))
}

// ProviderTradeNoContains applies the Contains predicate on the "provider_trade_no" field.
func ProviderTradeNoContains(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContains(FieldProviderTradeNo, v))
}

// ProviderTradeNoHasPrefix applies the HasPrefix predicate on the "provider_trade_no" field.
func ProviderTradeNoHasPrefix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasPrefix(FieldProviderTradeNo, v))
}

// ProviderTradeNoHasSuffix applies the HasSuffix predicate on the "provider_trade_no" field.
func ProviderTradeNoHasSuffix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasSuffix(FieldProviderTradeNo, v))
}

// ProviderTradeNoIsNil applies the IsNil predicate on the "provider_trade_no" field.
func ProviderTradeNoIsNil() predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIsNull(FieldProviderTradeNo))
}

// ProviderTradeNoNotNil applies the NotNil predicate on the "provider_trade_no" field.
func ProviderTradeNoNotNil() predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotNull(FieldProviderTradeNo))
}

// ProviderTradeNoEqualFold applies the EqualFold predicate on the "provider_trade_no" field.
func ProviderTradeNoEqualFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEqualFold(FieldProviderTradeNo, v))
}

// ProviderTradeNoContainsFold applies the ContainsFold predicate on the "provider_trade_no" field.
func ProviderTradeNoContainsFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContainsFold(FieldProviderTradeNo, v))
}

// AmountCentsEQ applies the EQ predicate on the "amount_cents" field.
func AmountCentsEQ(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldAmountCents, v))
}

// AmountCentsNEQ applies the NEQ predicate on the "amount_cents" field.
func AmountCentsNEQ(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldAmountCents, v))
}

// AmountCentsIn applies the In predicate on the "amount_cents" field.
func AmountCentsIn(vs ...int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldAmountCents, vs...))
}

// AmountCentsNotIn applies the NotIn predicate on the "amount_cents" field.
func AmountCentsNotIn(vs ...int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldAmountCents, vs...))
}

// AmountCentsGT applies the GT predicate on the "amount_cents" field.
func AmountCentsGT(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldAmountCents, v))
}

// AmountCentsGTE applies the GTE predicate on the "amount_cents" field.
func AmountCentsGTE(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldAmountCents, v))
}

// AmountCentsLT applies the LT predicate on the "amount_cents" field.
func AmountCentsLT(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldAmountCents, v))
}

// AmountCentsLTE applies the LTE predicate on the "amount_cents" field.
func AmountCentsLTE(v int64) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldAmountCents, v))
}

// AmountCentsIsNil applies the IsNil predicate on the "amount_cents" field.
func AmountCentsIsNil() predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIsNull(FieldAmountCents))
}

// AmountCentsNotNil applies the NotNil predicate on the "amount_cents" field.
func AmountCentsNotNil() predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotNull(FieldAmountCents))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyIsNil applies the IsNil predicate on the "currency" field.
func CurrencyIsNil() predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIsNull(FieldCurrency))
}

// CurrencyNotNil applies the NotNil predicate on the "currency" field.
func CurrencyNotNil() predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotNull(FieldCurrency))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContainsFold(FieldCurrency, v))
}

// VerifiedEQ applies the EQ predicate on the "verified" field.
func VerifiedEQ(v bool) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldVerified, v))
}

// VerifiedNEQ applies the NEQ predicate on the "verified" field.
func VerifiedNEQ(v bool) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldVerified, v))
}

// ProcessedEQ applies the EQ predicate on the "processed" field.
func ProcessedEQ(v bool) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldProcessed, v))
}

// ProcessedNEQ applies the NEQ predicate on the "processed" field.
func ProcessedNEQ(v bool) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldProcessed, v))
}

// ProcessErrorEQ applies the EQ predicate on the "process_error" field.
func ProcessErrorEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldProcessError, v))
}

// ProcessErrorNEQ applies the NEQ predicate on the "process_error" field.
func ProcessErrorNEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldProcessError, v))
}

// ProcessErrorIn applies the In predicate on the "process_error" field.
func ProcessErrorIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldProcessError, vs...))
}

// ProcessErrorNotIn applies the NotIn predicate on the "process_error" field.
func ProcessErrorNotIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldProcessError, vs...))
}

// ProcessErrorGT applies the GT predicate on the "process_error" field.
func ProcessErrorGT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldProcessError, v))
}

// ProcessErrorGTE applies the GTE predicate on the "process_error" field.
func ProcessErrorGTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldProcessError, v))
}

// ProcessErrorLT applies the LT predicate on the "process_error" field.
func ProcessErrorLT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldProcessError, v))
}

// ProcessErrorLTE applies the LTE predicate on the "process_error" field.
func ProcessErrorLTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldProcessError, v))
}

// ProcessErrorContains applies the Contains predicate on the "process_error" field.
func ProcessErrorContains(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContains(FieldProcessError, v))
}

// ProcessErrorHasPrefix applies the HasPrefix predicate on the "process_error" field.
func ProcessErrorHasPrefix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasPrefix(FieldProcessError, v))
}

// ProcessErrorHasSuffix applies the HasSuffix predicate on the "process_error" field.
func ProcessErrorHasSuffix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasSuffix(FieldProcessError, v))
}

// ProcessErrorIsNil applies the IsNil predicate on the "process_error" field.
func ProcessErrorIsNil() predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIsNull(FieldProcessError))
}

// ProcessErrorNotNil applies the NotNil predicate on the "process_error" field.
func ProcessErrorNotNil() predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotNull(FieldProcessError))
}

// ProcessErrorEqualFold applies the EqualFold predicate on the "process_error" field.
func ProcessErrorEqualFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEqualFold(FieldProcessError, v))
}

// ProcessErrorContainsFold applies the ContainsFold predicate on the "process_error" field.
func ProcessErrorContainsFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContainsFold(FieldProcessError, v))
}

// RawBodyEQ applies the EQ predicate on the "raw_body" field.
func RawBodyEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldRawBody, v))
}

// RawBodyNEQ applies the NEQ predicate on the "raw_body" field.
func RawBodyNEQ(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldRawBody, v))
}

// RawBodyIn applies the In predicate on the "raw_body" field.
func RawBodyIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldRawBody, vs...))
}

// RawBodyNotIn applies the NotIn predicate on the "raw_body" field.
func RawBodyNotIn(vs ...string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldRawBody, vs...))
}

// RawBodyGT applies the GT predicate on the "raw_body" field.
func RawBodyGT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldRawBody, v))
}

// RawBodyGTE applies the GTE predicate on the "raw_body" field.
func RawBodyGTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldRawBody, v))
}

// RawBodyLT applies the LT predicate on the "raw_body" field.
func RawBodyLT(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldRawBody, v))
}

// RawBodyLTE applies the LTE predicate on the "raw_body" field.
func RawBodyLTE(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldRawBody, v))
}

// RawBodyContains applies the Contains predicate on the "raw_body" field.
func RawBodyContains(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContains(FieldRawBody, v))
}

// RawBodyHasPrefix applies the HasPrefix predicate on the "raw_body" field.
func RawBodyHasPrefix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasPrefix(FieldRawBody, v))
}

// RawBodyHasSuffix applies the HasSuffix predicate on the "raw_body" field.
func RawBodyHasSuffix(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldHasSuffix(FieldRawBody, v))
}

// RawBodyEqualFold applies the EqualFold predicate on the "raw_body" field.
func RawBodyEqualFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEqualFold(FieldRawBody, v))
}

// RawBodyContainsFold applies the ContainsFold predicate on the "raw_body" field.
func RawBodyContainsFold(v string) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldContainsFold(FieldRawBody, v))
}

// ReceivedAtEQ applies the EQ predicate on the "received_at" field.
func ReceivedAtEQ(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldEQ(FieldReceivedAt, v))
}

// ReceivedAtNEQ applies the NEQ predicate on the "received_at" field.
func ReceivedAtNEQ(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNEQ(FieldReceivedAt, v))
}

// ReceivedAtIn applies the In predicate on the "received_at" field.
func ReceivedAtIn(vs ...time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldIn(FieldReceivedAt, vs...))
}

// ReceivedAtNotIn applies the NotIn predicate on the "received_at" field.
func ReceivedAtNotIn(vs ...time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldNotIn(FieldReceivedAt, vs...))
}

// ReceivedAtGT applies the GT predicate on the "received_at" field.
func ReceivedAtGT(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGT(FieldReceivedAt, v))
}

// ReceivedAtGTE applies the GTE predicate on the "received_at" field.
func ReceivedAtGTE(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldGTE(FieldReceivedAt, v))
}

// ReceivedAtLT applies the LT predicate on the "received_at" field.
func ReceivedAtLT(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLT(FieldReceivedAt, v))
}

// ReceivedAtLTE applies the LTE predicate on the "received_at" field.
func ReceivedAtLTE(v time.Time) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.FieldLTE(FieldReceivedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentNotification) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentNotification) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentNotification) predicate.PaymentNotification {
	return predicate.PaymentNotification(sql.NotPredicates(p))
}
