// Code generated by ent, DO NOT EDIT.

package paymentproduct

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the paymentproduct type in the database.
	Label = "payment_product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescriptionMd holds the string denoting the description_md field in the database.
	FieldDescriptionMd = "description_md"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldPriceCents holds the string denoting the price_cents field in the database.
	FieldPriceCents = "price_cents"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldValidityDays holds the string denoting the validity_days field in the database.
	FieldValidityDays = "validity_days"
	// FieldCreditBalance holds the string denoting the credit_balance field in the database.
	FieldCreditBalance = "credit_balance"
	// FieldAllowCustomAmount holds the string denoting the allow_custom_amount field in the database.
	FieldAllowCustomAmount = "allow_custom_amount"
	// FieldMinAmountCents holds the string denoting the min_amount_cents field in the database.
	FieldMinAmountCents = "min_amount_cents"
	// FieldMaxAmountCents holds the string denoting the max_amount_cents field in the database.
	FieldMaxAmountCents = "max_amount_cents"
	// FieldSuggestedAmountsCents holds the string denoting the suggested_amounts_cents field in the database.
	FieldSuggestedAmountsCents = "suggested_amounts_cents"
	// FieldExchangeRate holds the string denoting the exchange_rate field in the database.
	FieldExchangeRate = "exchange_rate"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeOrders holds the string denoting the orders edge name in mutations.
	EdgeOrders = "orders"
	// Table holds the table name of the paymentproduct in the database.
	Table = "payment_products"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "payment_products"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// OrdersTable is the table that holds the orders relation/edge.
	OrdersTable = "payment_orders"
	// OrdersInverseTable is the table name for the PaymentOrder entity.
	// It exists in this package in order to avoid circular dependency with the "paymentorder" package.
	OrdersInverseTable = "payment_orders"
	// OrdersColumn is the table column denoting the orders relation/edge.
	OrdersColumn = "product_id"
)

// Columns holds all SQL columns for paymentproduct fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldKind,
	FieldName,
	FieldDescriptionMd,
	FieldStatus,
	FieldSortOrder,
	FieldCurrency,
	FieldPriceCents,
	FieldGroupID,
	FieldValidityDays,
	FieldCreditBalance,
	FieldAllowCustomAmount,
	FieldMinAmountCents,
	FieldMaxAmountCents,
	FieldSuggestedAmountsCents,
	FieldExchangeRate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescriptionMd holds the default value on creation for the "description_md" field.
	DefaultDescriptionMd string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultPriceCents holds the default value on creation for the "price_cents" field.
	DefaultPriceCents int64
	// DefaultAllowCustomAmount holds the default value on creation for the "allow_custom_amount" field.
	DefaultAllowCustomAmount bool
)

// OrderOption defines the ordering options for the PaymentProduct queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescriptionMd orders the results by the description_md field.
func ByDescriptionMd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescriptionMd, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByPriceCents orders the results by the price_cents field.
func ByPriceCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceCents, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByValidityDays orders the results by the validity_days field.
func ByValidityDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidityDays, opts...).ToFunc()
}

// ByCreditBalance orders the results by the credit_balance field.
func ByCreditBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditBalance, opts...).ToFunc()
}

// ByAllowCustomAmount orders the results by the allow_custom_amount field.
func ByAllowCustomAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowCustomAmount, opts...).ToFunc()
}

// ByMinAmountCents orders the results by the min_amount_cents field.
func ByMinAmountCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinAmountCents, opts...).ToFunc()
}

// ByMaxAmountCents orders the results by the max_amount_cents field.
func ByMaxAmountCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxAmountCents, opts...).ToFunc()
}

// ByExchangeRate orders the results by the exchange_rate field.
func ByExchangeRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchangeRate, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByOrdersCount orders the results by orders count.
func ByOrdersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrdersStep(), opts...)
	}
}

// ByOrders orders the results by orders terms.
func ByOrders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrdersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newOrdersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrdersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
	)
}
