// Code generated by ent, DO NOT EDIT.

package paymentproduct

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldKind, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldName, v))
}

// DescriptionMd applies equality check predicate on the "description_md" field. It's identical to DescriptionMdEQ.
func DescriptionMd(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldDescriptionMd, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldStatus, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldSortOrder, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldCurrency, v))
}

// PriceCents applies equality check predicate on the "price_cents" field. It's identical to PriceCentsEQ.
func PriceCents(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldPriceCents, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldGroupID, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldValidityDays, v))
}

// CreditBalance applies equality check predicate on the "credit_balance" field. It's identical to CreditBalanceEQ.
func CreditBalance(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldCreditBalance, v))
}

// AllowCustomAmount applies equality check predicate on the "allow_custom_amount" field. It's identical to AllowCustomAmountEQ.
func AllowCustomAmount(v bool) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldAllowCustomAmount, v))
}

// MinAmountCents applies equality check predicate on the "min_amount_cents" field. It's identical to MinAmountCentsEQ.
func MinAmountCents(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldMinAmountCents, v))
}

// MaxAmountCents applies equality check predicate on the "max_amount_cents" field. It's identical to MaxAmountCentsEQ.
func MaxAmountCents(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldMaxAmountCents, v))
}

// ExchangeRate applies equality check predicate on the "exchange_rate" field. It's identical to ExchangeRateEQ.
func ExchangeRate(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldExchangeRate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldUpdatedAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldContainsFold(FieldKind, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldContainsFold(FieldName, v))
}

// DescriptionMdEQ applies the EQ predicate on the "description_md" field.
func DescriptionMdEQ(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldDescriptionMd, v))
}

// DescriptionMdNEQ applies the NEQ predicate on the "description_md" field.
func DescriptionMdNEQ(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldDescriptionMd, v))
}

// DescriptionMdIn applies the In predicate on the "description_md" field.
func DescriptionMdIn(vs ...string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldDescriptionMd, vs...))
}

// DescriptionMdNotIn applies the NotIn predicate on the "description_md" field.
func DescriptionMdNotIn(vs ...string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldDescriptionMd, vs...))
}

// DescriptionMdGT applies the GT predicate on the "description_md" field.
func DescriptionMdGT(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldDescriptionMd, v))
}

// DescriptionMdGTE applies the GTE predicate on the "description_md" field.
func DescriptionMdGTE(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldDescriptionMd, v))
}

// DescriptionMdLT applies the LT predicate on the "description_md" field.
func DescriptionMdLT(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldDescriptionMd, v))
}

// DescriptionMdLTE applies the LTE predicate on the "description_md" field.
func DescriptionMdLTE(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldDescriptionMd, v))
}

// DescriptionMdContains applies the Contains predicate on the "description_md" field.
func DescriptionMdContains(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldContains(FieldDescriptionMd, v))
}

// DescriptionMdHasPrefix applies the HasPrefix predicate on the "description_md" field.
func DescriptionMdHasPrefix(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldHasPrefix(FieldDescriptionMd, v))
}

// DescriptionMdHasSuffix applies the HasSuffix predicate on the "description_md" field.
func DescriptionMdHasSuffix(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldHasSuffix(FieldDescriptionMd, v))
}

// DescriptionMdEqualFold applies the EqualFold predicate on the "description_md" field.
func DescriptionMdEqualFold(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEqualFold(FieldDescriptionMd, v))
}

// DescriptionMdContainsFold applies the ContainsFold predicate on the "description_md" field.
func DescriptionMdContainsFold(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldContainsFold(FieldDescriptionMd, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldContainsFold(FieldStatus, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldSortOrder, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldContainsFold(FieldCurrency, v))
}

// PriceCentsEQ applies the EQ predicate on the "price_cents" field.
func PriceCentsEQ(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldPriceCents, v))
}

// PriceCentsNEQ applies the NEQ predicate on the "price_cents" field.
func PriceCentsNEQ(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldPriceCents, v))
}

// PriceCentsIn applies the In predicate on the "price_cents" field.
func PriceCentsIn(vs ...int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldPriceCents, vs...))
}

// PriceCentsNotIn applies the NotIn predicate on the "price_cents" field.
func PriceCentsNotIn(vs ...int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldPriceCents, vs...))
}

// PriceCentsGT applies the GT predicate on the "price_cents" field.
func PriceCentsGT(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldPriceCents, v))
}

// PriceCentsGTE applies the GTE predicate on the "price_cents" field.
func PriceCentsGTE(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldPriceCents, v))
}

// PriceCentsLT applies the LT predicate on the "price_cents" field.
func PriceCentsLT(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldPriceCents, v))
}

// PriceCentsLTE applies the LTE predicate on the "price_cents" field.
func PriceCentsLTE(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldPriceCents, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotNull(FieldGroupID))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldValidityDays, v))
}

// ValidityDaysIsNil applies the IsNil predicate on the "validity_days" field.
func ValidityDaysIsNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIsNull(FieldValidityDays))
}

// ValidityDaysNotNil applies the NotNil predicate on the "validity_days" field.
func ValidityDaysNotNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotNull(FieldValidityDays))
}

// CreditBalanceEQ applies the EQ predicate on the "credit_balance" field.
func CreditBalanceEQ(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldCreditBalance, v))
}

// CreditBalanceNEQ applies the NEQ predicate on the "credit_balance" field.
func CreditBalanceNEQ(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldCreditBalance, v))
}

// CreditBalanceIn applies the In predicate on the "credit_balance" field.
func CreditBalanceIn(vs ...float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldCreditBalance, vs...))
}

// CreditBalanceNotIn applies the NotIn predicate on the "credit_balance" field.
func CreditBalanceNotIn(vs ...float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldCreditBalance, vs...))
}

// CreditBalanceGT applies the GT predicate on the "credit_balance" field.
func CreditBalanceGT(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldCreditBalance, v))
}

// CreditBalanceGTE applies the GTE predicate on the "credit_balance" field.
func CreditBalanceGTE(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldCreditBalance, v))
}

// CreditBalanceLT applies the LT predicate on the "credit_balance" field.
func CreditBalanceLT(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldCreditBalance, v))
}

// CreditBalanceLTE applies the LTE predicate on the "credit_balance" field.
func CreditBalanceLTE(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldCreditBalance, v))
}

// CreditBalanceIsNil applies the IsNil predicate on the "credit_balance" field.
func CreditBalanceIsNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIsNull(FieldCreditBalance))
}

// CreditBalanceNotNil applies the NotNil predicate on the "credit_balance" field.
func CreditBalanceNotNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotNull(FieldCreditBalance))
}

// AllowCustomAmountEQ applies the EQ predicate on the "allow_custom_amount" field.
func AllowCustomAmountEQ(v bool) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldAllowCustomAmount, v))
}

// AllowCustomAmountNEQ applies the NEQ predicate on the "allow_custom_amount" field.
func AllowCustomAmountNEQ(v bool) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldAllowCustomAmount, v))
}

// MinAmountCentsEQ applies the EQ predicate on the "min_amount_cents" field.
func MinAmountCentsEQ(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldMinAmountCents, v))
}

// MinAmountCentsNEQ applies the NEQ predicate on the "min_amount_cents" field.
func MinAmountCentsNEQ(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldMinAmountCents, v))
}

// MinAmountCentsIn applies the In predicate on the "min_amount_cents" field.
func MinAmountCentsIn(vs ...int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldMinAmountCents, vs...))
}

// MinAmountCentsNotIn applies the NotIn predicate on the "min_amount_cents" field.
func MinAmountCentsNotIn(vs ...int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldMinAmountCents, vs...))
}

// MinAmountCentsGT applies the GT predicate on the "min_amount_cents" field.
func MinAmountCentsGT(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldMinAmountCents, v))
}

// MinAmountCentsGTE applies the GTE predicate on the "min_amount_cents" field.
func MinAmountCentsGTE(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldMinAmountCents, v))
}

// MinAmountCentsLT applies the LT predicate on the "min_amount_cents" field.
func MinAmountCentsLT(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldMinAmountCents, v))
}

// MinAmountCentsLTE applies the LTE predicate on the "min_amount_cents" field.
func MinAmountCentsLTE(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldMinAmountCents, v))
}

// MinAmountCentsIsNil applies the IsNil predicate on the "min_amount_cents" field.
func MinAmountCentsIsNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIsNull(FieldMinAmountCents))
}

// MinAmountCentsNotNil applies the NotNil predicate on the "min_amount_cents" field.
func MinAmountCentsNotNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotNull(FieldMinAmountCents))
}

// MaxAmountCentsEQ applies the EQ predicate on the "max_amount_cents" field.
func MaxAmountCentsEQ(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldMaxAmountCents, v))
}

// MaxAmountCentsNEQ applies the NEQ predicate on the "max_amount_cents" field.
func MaxAmountCentsNEQ(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldMaxAmountCents, v))
}

// MaxAmountCentsIn applies the In predicate on the "max_amount_cents" field.
func MaxAmountCentsIn(vs ...int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldMaxAmountCents, vs...))
}

// MaxAmountCentsNotIn applies the NotIn predicate on the "max_amount_cents" field.
func MaxAmountCentsNotIn(vs ...int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldMaxAmountCents, vs...))
}

// MaxAmountCentsGT applies the GT predicate on the "max_amount_cents" field.
func MaxAmountCentsGT(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldMaxAmountCents, v))
}

// MaxAmountCentsGTE applies the GTE predicate on the "max_amount_cents" field.
func MaxAmountCentsGTE(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldMaxAmountCents, v))
}

// MaxAmountCentsLT applies the LT predicate on the "max_amount_cents" field.
func MaxAmountCentsLT(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldMaxAmountCents, v))
}

// MaxAmountCentsLTE applies the LTE predicate on the "max_amount_cents" field.
func MaxAmountCentsLTE(v int64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldMaxAmountCents, v))
}

// MaxAmountCentsIsNil applies the IsNil predicate on the "max_amount_cents" field.
func MaxAmountCentsIsNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIsNull(FieldMaxAmountCents))
}

// MaxAmountCentsNotNil applies the NotNil predicate on the "max_amount_cents" field.
func MaxAmountCentsNotNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotNull(FieldMaxAmountCents))
}

// SuggestedAmountsCentsIsNil applies the IsNil predicate on the "suggested_amounts_cents" field.
func SuggestedAmountsCentsIsNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIsNull(FieldSuggestedAmountsCents))
}

// SuggestedAmountsCentsNotNil applies the NotNil predicate on the "suggested_amounts_cents" field.
func SuggestedAmountsCentsNotNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotNull(FieldSuggestedAmountsCents))
}

// ExchangeRateEQ applies the EQ predicate on the "exchange_rate" field.
func ExchangeRateEQ(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldEQ(FieldExchangeRate, v))
}

// ExchangeRateNEQ applies the NEQ predicate on the "exchange_rate" field.
func ExchangeRateNEQ(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNEQ(FieldExchangeRate, v))
}

// ExchangeRateIn applies the In predicate on the "exchange_rate" field.
func ExchangeRateIn(vs ...float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIn(FieldExchangeRate, vs...))
}

// ExchangeRateNotIn applies the NotIn predicate on the "exchange_rate" field.
func ExchangeRateNotIn(vs ...float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotIn(FieldExchangeRate, vs...))
}

// ExchangeRateGT applies the GT predicate on the "exchange_rate" field.
func ExchangeRateGT(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGT(FieldExchangeRate, v))
}

// ExchangeRateGTE applies the GTE predicate on the "exchange_rate" field.
func ExchangeRateGTE(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldGTE(FieldExchangeRate, v))
}

// ExchangeRateLT applies the LT predicate on the "exchange_rate" field.
func ExchangeRateLT(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLT(FieldExchangeRate, v))
}

// ExchangeRateLTE applies the LTE predicate on the "exchange_rate" field.
func ExchangeRateLTE(v float64) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldLTE(FieldExchangeRate, v))
}

// ExchangeRateIsNil applies the IsNil predicate on the "exchange_rate" field.
func ExchangeRateIsNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldIsNull(FieldExchangeRate))
}

// ExchangeRateNotNil applies the NotNil predicate on the "exchange_rate" field.
func ExchangeRateNotNil() predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.FieldNotNull(FieldExchangeRate))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.PaymentProduct {
	return predicate.PaymentProduct(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.PaymentProduct {
	return predicate.PaymentProduct(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrders applies the HasEdge predicate on the "orders" edge.
func HasOrders() predicate.PaymentProduct {
	return predicate.PaymentProduct(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrdersWith applies the HasEdge predicate on the "orders" edge with a given conditions (other predicates).
func HasOrdersWith(preds ...predicate.PaymentOrder) predicate.PaymentProduct {
	return predicate.PaymentProduct(func(s *sql.Selector) {
		step := newOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentProduct) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentProduct) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentProduct) predicate.PaymentProduct {
	return predicate.PaymentProduct(sql.NotPredicates(p))
}
